/** @type {import('tailwindcss').Config} */
export default {
  content: ['./client/src/**/*.{ts,tsx}', './client/index.html'],
  theme: {
    extend: {
      colors: {
        ink: '#0D0D0D',
        terra: {
          DEFAULT: '#D4714E',
          hover: '#c2613f',
          soft: '#FFF0EB',
          glow: 'rgba(212, 113, 78, 0.12)',
        },
        /* stone removed — was conflicting with Tailwind's built-in stone palette */
        surface: '#f9f9f9',
        tint: '#f9f9f9',
        cream: {
          DEFAULT: '#F5F3EF',
          deep: '#F5F5F5',
          dark: '#EEEEEE',
          hover: '#E8E8E8',
        },
        border: 'rgba(0,0,0,0.06)',
        text: {
          DEFAULT: '#0D0D0D',
          primary: '#0D0D0D',
          mid: 'rgba(0,0,0,0.6)',
          secondary: 'rgba(0,0,0,0.4)',
          tertiary: 'rgba(0,0,0,0.3)',
          muted: 'rgba(0,0,0,0.4)',
          faint: 'rgba(0,0,0,0.25)',
        },
        /* Stitch / Material Design 3 palette */
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#55433d',
        'on-background': '#1a1c1c',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-primary-container': '#fcfcfc',
        'on-secondary-container': '#646464',
        'on-tertiary-container': '#fffbff',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#1b1b1b',
        'on-primary-fixed-variant': '#474747',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        'on-tertiary-fixed': '#3a0a00',
        'on-tertiary-fixed-variant': '#7a2f18',
        primary: '#5c5c5c',
        'primary-container': '#747474',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c6',
        secondary: '#5e5e5e',
        'secondary-container': '#e4e2e2',
        'secondary-fixed': '#e4e2e2',
        'secondary-fixed-dim': '#c8c6c6',
        tertiary: '#95432b',
        'tertiary-container': '#b45b40',
        'tertiary-fixed': '#ffdbd1',
        'tertiary-fixed-dim': '#ffb59f',
        background: '#f9f9f9',
        'surface-bright': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#5e5e5e',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        'inverse-primary': '#c6c6c6',
        outline: '#88726c',
        'outline-variant': '#dbc1ba',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        '4xl': '34px',
      },
      fontFamily: {
        serif: ['PT Serif', 'Georgia', 'serif'],
        display: ['Playfair Display', 'serif'],
        headline: ['PT Serif', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      maxWidth: {
        site: '1200px',
        'chat-card': '768px',
      },
    },
  },
  plugins: [],
};
