/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./client/src/**/*.{ts,tsx}', './client/index.html'],
  theme: {
    extend: {
      colors: {
        /* Legacy tokens — kept for internal app components */
        ink: '#0D0D0D',
        terra: {
          DEFAULT: '#b0004a',
          hover: '#90003b',
          soft: '#ffd9de',
          glow: 'rgba(176, 0, 74, 0.12)',
        },
        cream: {
          DEFAULT: '#f3f3f6',
          deep: '#eeeef0',
          dark: '#e8e8ea',
          hover: '#e2e2e5',
        },
        border: 'rgba(0,0,0,0.06)',
        text: {
          DEFAULT: '#1a1c1e',
          primary: '#1a1c1e',
          mid: '#5d5e61',
          secondary: '#636467',
          tertiary: '#8e6f74',
          muted: '#636467',
          faint: '#c6c6c9',
        },

        /* ═══ Stitch V2 — Material Design 3 (pink-rose) ═══ */
        primary: '#b0004a',
        'primary-container': '#d81b60',
        'primary-fixed': '#ffd9de',
        'primary-fixed-dim': '#ffb2bf',
        secondary: '#5d5e61',
        'secondary-container': '#e2e2e5',
        'secondary-fixed': '#e2e2e5',
        'secondary-fixed-dim': '#c6c6c9',
        tertiary: '#006630',
        'tertiary-container': '#00823f',
        'tertiary-fixed': '#8ff9a8',
        'tertiary-fixed-dim': '#73dc8e',
        error: '#ba1a1a',
        'error-container': '#ffdad6',

        background: '#f9f9fc',
        surface: '#f9f9fc',
        'surface-bright': '#f9f9fc',
        'surface-dim': '#dadadc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f6',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'surface-variant': '#e2e2e5',
        'surface-tint': '#bc004f',

        'inverse-surface': '#2f3133',
        'inverse-on-surface': '#f0f0f3',
        'inverse-primary': '#ffb2bf',

        'on-surface': '#1a1c1e',
        'on-surface-variant': '#5a4044',
        'on-background': '#1a1c1e',
        'on-primary': '#ffffff',
        'on-primary-container': '#fff2f3',
        'on-primary-fixed': '#3f0016',
        'on-primary-fixed-variant': '#90003b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#636467',
        'on-secondary-fixed': '#1a1c1e',
        'on-secondary-fixed-variant': '#454749',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#dcffdd',
        'on-tertiary-fixed': '#00210b',
        'on-tertiary-fixed-variant': '#005226',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        outline: '#8e6f74',
        'outline-variant': '#e3bdc3',
      },
      borderRadius: {
        '4xl': '34px',
      },
      fontFamily: {
        headline: ['Sora', 'sans-serif'],
        display: ['Sora', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        handwritten: ['Caveat', 'cursive'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      maxWidth: {
        site: '1200px',
        'chat-card': '768px',
      },
    },
  },
  plugins: [],
};
