/**
 * ArtifactSheet — full-screen Vaul sheet for viewing Yulia's generated
 * deliverables (CIM, valuation, DCF, thesis, screening memo, SBA model).
 *
 * Replaces the desktop canvas tab on mobile. When the user taps a
 * deliverable card in chat, this sheet opens bottom-up with the rendered
 * artifact + action row (Ask Yulia, Share, Export).
 *
 * Mobile only. Desktop continues to use openCanvasTab.
 */

import { Drawer } from 'vaul';
import { useEffect, useMemo, useRef, useState } from 'react';
import Markdown from 'react-markdown';

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  dark: boolean;
  /** Display title (e.g., "Valuation Report — Acme Industries") */
  title: string;
  /** Optional subtitle (e.g., "Generated by Yulia · 3 minutes ago") */
  subtitle?: string;
  /** Material icon name shown in the header badge */
  icon?: string;
  /** Rendered artifact body — markdown already converted to JSX or plain text */
  children: React.ReactNode;
  /** Pre-fill text for "Ask Yulia" — sends user back to chat with the pill populated */
  onAskYulia?: (prefill: string) => void;
  /** Hook for iOS share sheet — if provided, shows a Share button */
  onShare?: () => void;
  /** Hook for PDF export — if provided, shows an Export button */
  onExport?: () => void;
}

const PINK = '#D44A78';
const PINK_DARK = '#E8709A';

export function ArtifactSheet({
  open,
  onOpenChange,
  dark,
  title,
  subtitle,
  icon = 'description',
  children,
  onAskYulia,
  onShare,
  onExport,
}: Props) {
  const [scrolled, setScrolled] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) {
      setScrolled(false);
      if (scrollRef.current) scrollRef.current.scrollTop = 0;
    }
  }, [open]);

  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    setScrolled(e.currentTarget.scrollTop > 16);
  };

  // Tokens
  const bg = dark ? '#151617' : '#fefefe';
  const headingC = dark ? '#f9f9fc' : '#0f1012';
  const bodyC = dark ? 'rgba(218,218,220,0.85)' : '#3c3d40';
  const mutedC = dark ? 'rgba(218,218,220,0.55)' : '#7c7d80';
  const borderC = dark ? 'rgba(255,255,255,0.08)' : 'rgba(15,16,18,0.08)';
  const pinkC = dark ? PINK_DARK : PINK;
  const chipBg = dark ? '#1f2123' : '#f5f5f7';

  const handleAsk = () => {
    onAskYulia?.(`About this ${title.toLowerCase()} — `);
    onOpenChange(false);
  };

  return (
    <Drawer.Root open={open} onOpenChange={onOpenChange} shouldScaleBackground>
      <Drawer.Portal>
        <Drawer.Overlay
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0,0,0,0.45)',
            zIndex: 90,
          }}
        />
        <Drawer.Content
          style={{
            position: 'fixed',
            bottom: 0,
            left: 0,
            right: 0,
            height: '92vh',
            maxHeight: '92dvh',
            background: bg,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            display: 'flex',
            flexDirection: 'column',
            zIndex: 100,
            outline: 'none',
          }}
        >
          {/* Drag handle */}
          <div style={{ display: 'flex', justifyContent: 'center', padding: '10px 0 4px' }}>
            <div
              style={{
                width: 40,
                height: 5,
                borderRadius: 999,
                background: dark ? 'rgba(255,255,255,0.18)' : 'rgba(15,16,18,0.16)',
              }}
            />
          </div>

          {/* Header */}
          <div
            style={{
              padding: '8px 16px 14px',
              borderBottom: scrolled ? `1px solid ${borderC}` : '1px solid transparent',
              transition: 'border-color 200ms',
              display: 'flex',
              alignItems: 'center',
              gap: 12,
            }}
          >
            <div
              style={{
                width: 36,
                height: 36,
                borderRadius: 10,
                background: chipBg,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
              }}
            >
              <span className="material-symbols-outlined" style={{ color: pinkC, fontSize: 20 }}>
                {icon}
              </span>
            </div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <Drawer.Title asChild>
                <h2
                  style={{
                    margin: 0,
                    fontFamily: 'Sora, system-ui',
                    fontSize: 17,
                    fontWeight: 800,
                    letterSpacing: '-0.01em',
                    color: headingC,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {title}
                </h2>
              </Drawer.Title>
              {subtitle && (
                <p
                  style={{
                    margin: '2px 0 0',
                    fontFamily: 'Inter, system-ui',
                    fontSize: 12,
                    fontWeight: 500,
                    color: mutedC,
                  }}
                >
                  {subtitle}
                </p>
              )}
            </div>
            <button
              onClick={() => onOpenChange(false)}
              type="button"
              aria-label="Close"
              style={{
                width: 32,
                height: 32,
                borderRadius: '50%',
                border: 'none',
                background: chipBg,
                color: bodyC,
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
                WebkitTapHighlightColor: 'transparent',
              }}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                <path d="M18 6L6 18M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Scrollable body — markdown rendering for Yulia deliverables */}
          <div
            ref={scrollRef}
            onScroll={handleScroll}
            className="artifact-sheet-prose"
            style={{
              flex: 1,
              overflowY: 'auto',
              WebkitOverflowScrolling: 'touch',
              padding: '18px 18px 32px',
              color: bodyC,
              fontFamily: 'Inter, system-ui',
              fontSize: 15,
              lineHeight: 1.6,
            }}
          >
            {children}
            <style>{`
              .artifact-sheet-prose h1 { font-family: Sora, system-ui; font-size: 24px; font-weight: 800; letter-spacing: -0.02em; color: ${headingC}; margin: 0 0 12px; line-height: 1.2; }
              .artifact-sheet-prose h2 { font-family: Sora, system-ui; font-size: 19px; font-weight: 700; letter-spacing: -0.015em; color: ${headingC}; margin: 24px 0 8px; line-height: 1.25; }
              .artifact-sheet-prose h3 { font-family: Sora, system-ui; font-size: 16px; font-weight: 700; color: ${headingC}; margin: 18px 0 6px; line-height: 1.3; }
              .artifact-sheet-prose h4 { font-family: Inter, system-ui; font-size: 14px; font-weight: 700; color: ${headingC}; margin: 14px 0 4px; text-transform: uppercase; letter-spacing: 0.04em; }
              .artifact-sheet-prose p { margin: 0 0 14px; }
              .artifact-sheet-prose ul, .artifact-sheet-prose ol { margin: 0 0 14px; padding-left: 22px; }
              .artifact-sheet-prose li { margin-bottom: 6px; }
              .artifact-sheet-prose li::marker { color: ${pinkC}; }
              .artifact-sheet-prose strong { color: ${headingC}; font-weight: 700; }
              .artifact-sheet-prose em { color: ${bodyC}; }
              .artifact-sheet-prose code { font-family: 'JetBrains Mono', ui-monospace, Menlo, monospace; font-size: 13px; background: ${chipBg}; color: ${headingC}; padding: 2px 6px; border-radius: 6px; }
              .artifact-sheet-prose pre { background: ${chipBg}; border: 1px solid ${borderC}; border-radius: 10px; padding: 12px; overflow-x: auto; font-size: 13px; }
              .artifact-sheet-prose pre code { background: transparent; padding: 0; }
              .artifact-sheet-prose blockquote { border-left: 3px solid ${pinkC}; padding: 4px 12px; margin: 12px 0; color: ${mutedC}; font-style: italic; }
              .artifact-sheet-prose table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 12px 0; }
              .artifact-sheet-prose th, .artifact-sheet-prose td { border-bottom: 1px solid ${borderC}; padding: 8px 10px; text-align: left; }
              .artifact-sheet-prose th { font-family: Sora, system-ui; font-weight: 700; color: ${headingC}; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; }
              .artifact-sheet-prose hr { border: none; border-top: 1px solid ${borderC}; margin: 18px 0; }
              .artifact-sheet-prose a { color: ${pinkC}; text-decoration: underline; text-decoration-thickness: 1px; text-underline-offset: 2px; }
            `}</style>
          </div>

          {/* Footer actions */}
          {(onAskYulia || onShare || onExport) && (
            <div
              style={{
                padding: '12px 16px calc(12px + env(safe-area-inset-bottom))',
                borderTop: `1px solid ${borderC}`,
                display: 'flex',
                gap: 8,
                background: bg,
              }}
            >
              {onAskYulia && (
                <button
                  onClick={handleAsk}
                  type="button"
                  style={{
                    flex: 1,
                    padding: '12px 16px',
                    borderRadius: 12,
                    border: 'none',
                    background: pinkC,
                    color: '#fff',
                    fontFamily: 'Inter, system-ui',
                    fontSize: 14,
                    fontWeight: 700,
                    cursor: 'pointer',
                    display: 'inline-flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: 6,
                    WebkitTapHighlightColor: 'transparent',
                  }}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: 16 }}>chat_bubble</span>
                  Ask Yulia
                </button>
              )}
              {onShare && (
                <button
                  onClick={onShare}
                  type="button"
                  aria-label="Share"
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: 12,
                    border: `1px solid ${borderC}`,
                    background: chipBg,
                    color: bodyC,
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                  }}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: 18 }}>ios_share</span>
                </button>
              )}
              {onExport && (
                <button
                  onClick={onExport}
                  type="button"
                  aria-label="Export"
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: 12,
                    border: `1px solid ${borderC}`,
                    background: chipBg,
                    color: bodyC,
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                  }}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: 18 }}>download</span>
                </button>
              )}
            </div>
          )}
        </Drawer.Content>
      </Drawer.Portal>
    </Drawer.Root>
  );
}

export default ArtifactSheet;
