DEFINITIVE_REFERENCE_SPEC_VERSION = "DEFINITIVE.v1.0"
DEFINITIVE_REFERENCE_METHODOLOGY_URI = "methodology://v19"
DEFINITIVE_REFERENCE_METHODOLOGY_VERSION = "v19"
DEFINITIVE_REFERENCE_PACKAGE_VERSION = "0.1.0"

REFERENCE_MODEL_IDS = {"M109", "M139", "M199", "M206"}
