import { useState, useEffect, useCallback } from 'react';
import Markdown from 'react-markdown';
import { authHeaders } from '../../hooks/useAuth';

interface CanvasProps {
  deliverableId: number | null;
  onClose: () => void;
}

interface DeliverableData {
  id: number;
  name: string;
  slug: string;
  tier: string;
  status: string;
  content: Record<string, any> | null;
  completed_at: string | null;
  generation_model: string | null;
  generation_time_ms: number | null;
}

export default function Canvas({ deliverableId, onClose }: CanvasProps) {
  const [data, setData] = useState<DeliverableData | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    if (!deliverableId) return;
    try {
      const res = await fetch(`/api/deliverables/${deliverableId}`, { headers: authHeaders() });
      if (res.ok) {
        const d = await res.json();
        setData(d);
        // Keep polling if still generating
        if (d.status === 'queued' || d.status === 'generating') {
          setTimeout(fetchData, 3000);
        }
      }
    } catch { /* ignore */ }
    finally { setLoading(false); }
  }, [deliverableId]);

  useEffect(() => {
    setLoading(true);
    setData(null);
    fetchData();
  }, [fetchData]);

  const handleExportPDF = () => {
    // Open print dialog as a PDF export fallback
    const printArea = document.getElementById('canvas-print-area');
    if (!printArea) return;
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(`
      <html><head><title>${data?.name || 'Deliverable'}</title>
      <style>
        body { font-family: 'Inter', system-ui, sans-serif; color: #1A1A18; padding: 40px; max-width: 800px; margin: 0 auto; line-height: 1.6; }
        h1, h2, h3 { font-weight: 700; margin-top: 1.5em; }
        h1 { font-size: 24px; border-bottom: 2px solid #D4714E; padding-bottom: 8px; }
        h2 { font-size: 18px; color: #3D3B37; }
        h3 { font-size: 15px; color: #6E6A63; }
        table { border-collapse: collapse; width: 100%; margin: 16px 0; }
        th, td { border: 1px solid #DDD9D1; padding: 8px 12px; text-align: left; font-size: 13px; }
        th { background: #F3F0EA; font-weight: 600; }
        ul, ol { padding-left: 24px; }
        .meta { color: #6E6A63; font-size: 12px; margin-bottom: 24px; }
      </style></head><body>
      <div class="meta">Generated by smbx.ai${data?.completed_at ? ` on ${new Date(data.completed_at).toLocaleDateString()}` : ''}</div>
      ${printArea.innerHTML}
      </body></html>
    `);
    w.document.close();
    w.print();
  };

  if (!deliverableId) return null;

  return (
    <div className="flex flex-col h-full bg-white">
      {/* Toolbar */}
      <div className="shrink-0 flex items-center justify-between px-4 py-2.5" style={{ borderBottom: '1px solid #DDD9D1' }}>
        <div className="flex items-center gap-2 min-w-0">
          <div className="w-6 h-6 rounded bg-[#D4714E] text-white flex items-center justify-center shrink-0">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" /><path d="M14 2v6h6" />
            </svg>
          </div>
          <span className="text-sm font-semibold text-[#1A1A18] truncate">{data?.name || 'Loading...'}</span>
          {data?.status && data.status !== 'complete' && (
            <span className={`text-[10px] font-semibold uppercase px-2 py-0.5 rounded-full shrink-0 ${
              data.status === 'generating' ? 'text-blue-600 bg-blue-50' : data.status === 'queued' ? 'text-yellow-600 bg-yellow-50' : 'text-red-600 bg-red-50'
            }`}>{data.status}</span>
          )}
        </div>
        <div className="flex items-center gap-1.5 shrink-0">
          {data?.status === 'complete' && (
            <button
              onClick={handleExportPDF}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-[#F3F0EA] text-[#3D3B37] border-0 cursor-pointer hover:bg-[#EBE7DF] transition-colors"
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Export
            </button>
          )}
          <button
            onClick={onClose}
            className="w-7 h-7 rounded-lg hover:bg-[#F3F0EA] flex items-center justify-center cursor-pointer border-0 bg-transparent transition-colors"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M18 6L6 18M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto min-h-0">
        {loading && (
          <div className="flex items-center justify-center p-12">
            <div className="flex flex-col items-center gap-3">
              <div className="w-8 h-8 border-2 border-[#D4714E] border-t-transparent rounded-full animate-spin" />
              <p className="text-sm text-[#6E6A63]">Loading deliverable...</p>
            </div>
          </div>
        )}

        {!loading && data?.status === 'generating' && (
          <div className="flex items-center justify-center p-12">
            <div className="flex flex-col items-center gap-3 text-center">
              <div className="w-12 h-12 border-2 border-[#D4714E] border-t-transparent rounded-full animate-spin" />
              <p className="text-base font-semibold text-[#1A1A18]">Generating your {data.name}...</p>
              <p className="text-sm text-[#6E6A63] max-w-xs">This typically takes 30-60 seconds. The document will appear here when ready.</p>
            </div>
          </div>
        )}

        {!loading && data?.status === 'queued' && (
          <div className="flex items-center justify-center p-12">
            <div className="flex flex-col items-center gap-3 text-center">
              <div className="w-10 h-10 rounded-full bg-yellow-50 flex items-center justify-center">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#ca8a04" strokeWidth="2"><circle cx="12" cy="12" r="10" /><polyline points="12 6 12 12 16 14" /></svg>
              </div>
              <p className="text-base font-semibold text-[#1A1A18]">In queue</p>
              <p className="text-sm text-[#6E6A63]">Your {data.name} will begin generating shortly.</p>
            </div>
          </div>
        )}

        {!loading && data?.status === 'complete' && data.content && (
          <div id="canvas-print-area" className="px-6 py-5 max-w-[700px] mx-auto canvas-content">
            <CanvasContent content={data.content} name={data.name} />
          </div>
        )}

        {!loading && data?.status === 'failed' && (
          <div className="flex items-center justify-center p-12">
            <div className="flex flex-col items-center gap-3 text-center">
              <div className="w-10 h-10 rounded-full bg-red-50 flex items-center justify-center">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#dc2626" strokeWidth="2"><circle cx="12" cy="12" r="10" /><line x1="15" y1="9" x2="9" y2="15" /><line x1="9" y1="9" x2="15" y2="15" /></svg>
              </div>
              <p className="text-base font-semibold text-[#1A1A18]">Generation failed</p>
              <p className="text-sm text-[#6E6A63]">Something went wrong. Please try again or contact support.</p>
            </div>
          </div>
        )}

        {!loading && !data && (
          <div className="flex items-center justify-center p-12">
            <p className="text-sm text-[#6E6A63]">Deliverable not found.</p>
          </div>
        )}
      </div>
    </div>
  );
}

function CanvasContent({ content, name }: { content: Record<string, any>; name: string }) {
  // If content has markdown field, render as markdown
  if (content.markdown) {
    return (
      <div className="canvas-md">
        <Markdown>{content.markdown}</Markdown>
      </div>
    );
  }

  // If content has sections array
  if (content.sections && Array.isArray(content.sections)) {
    return (
      <div className="space-y-6">
        <h1 className="text-xl font-bold text-[#1A1A18] m-0 pb-2" style={{ borderBottom: '2px solid #D4714E' }}>
          {name}
        </h1>
        {content.summary && (
          <div className="bg-[#FFF8F5] rounded-xl px-5 py-4" style={{ border: '1px solid rgba(212,113,78,.15)' }}>
            <p className="text-sm font-semibold text-[#D4714E] m-0 mb-1">Summary</p>
            <p className="text-sm text-[#3D3B37] leading-relaxed m-0">{content.summary}</p>
          </div>
        )}
        {content.sections.map((section: any, i: number) => (
          <div key={i}>
            <h2 className="text-base font-bold text-[#1A1A18] m-0 mb-2">{section.title}</h2>
            {typeof section.content === 'string' ? (
              <div className="text-sm text-[#3D3B37] leading-[1.7] whitespace-pre-wrap">{section.content}</div>
            ) : section.table ? (
              <CanvasTable data={section.table} />
            ) : section.items ? (
              <ul className="text-sm text-[#3D3B37] leading-[1.7] pl-5 m-0 space-y-1">
                {section.items.map((item: string, j: number) => <li key={j}>{item}</li>)}
              </ul>
            ) : (
              <div className="text-sm text-[#3D3B37] leading-[1.7]">
                <Markdown>{String(section.content || '')}</Markdown>
              </div>
            )}
          </div>
        ))}
        {content.disclaimer && (
          <div className="text-xs text-[#A9A49C] pt-4 mt-4" style={{ borderTop: '1px solid #EBE7DF' }}>
            {content.disclaimer}
          </div>
        )}
      </div>
    );
  }

  // Key-value format
  return (
    <div className="space-y-4">
      <h1 className="text-xl font-bold text-[#1A1A18] m-0 pb-2" style={{ borderBottom: '2px solid #D4714E' }}>
        {name}
      </h1>
      {Object.entries(content).map(([key, value]) => {
        if (key === 'type' || key === 'generated_at') return null;
        return (
          <div key={key} className="pb-3" style={{ borderBottom: '1px solid #EBE7DF' }}>
            <p className="text-xs font-semibold uppercase tracking-wider text-[#6E6A63] m-0 mb-1">
              {key.replace(/_/g, ' ')}
            </p>
            <div className="text-sm text-[#1A1A18]">
              {typeof value === 'string' ? (
                <span className="whitespace-pre-wrap">{value}</span>
              ) : typeof value === 'number' ? (
                <span className="font-semibold">{value.toLocaleString()}</span>
              ) : Array.isArray(value) ? (
                <ul className="pl-5 m-0 space-y-0.5">
                  {value.map((item, i) => <li key={i}>{typeof item === 'object' ? JSON.stringify(item) : String(item)}</li>)}
                </ul>
              ) : typeof value === 'object' && value !== null ? (
                <CanvasTable data={value} />
              ) : (
                <span>{String(value)}</span>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}

function CanvasTable({ data }: { data: any }) {
  if (Array.isArray(data) && data.length > 0 && typeof data[0] === 'object') {
    const headers = Object.keys(data[0]);
    return (
      <div className="overflow-x-auto rounded-lg" style={{ border: '1px solid #DDD9D1' }}>
        <table className="w-full text-sm" style={{ borderCollapse: 'collapse' }}>
          <thead>
            <tr className="bg-[#F3F0EA]">
              {headers.map(h => (
                <th key={h} className="text-left px-3 py-2 text-xs font-semibold text-[#3D3B37] uppercase tracking-wide" style={{ borderBottom: '1px solid #DDD9D1' }}>
                  {h.replace(/_/g, ' ')}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {data.map((row: any, i: number) => (
              <tr key={i} className={i % 2 ? 'bg-[#FAFAF8]' : ''}>
                {headers.map(h => (
                  <td key={h} className="px-3 py-2 text-[#1A1A18]" style={{ borderBottom: '1px solid #EBE7DF' }}>
                    {typeof row[h] === 'number' ? row[h].toLocaleString() : String(row[h] ?? '')}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }

  // Object as key-value table
  if (typeof data === 'object' && !Array.isArray(data)) {
    return (
      <div className="overflow-x-auto rounded-lg" style={{ border: '1px solid #DDD9D1' }}>
        <table className="w-full text-sm" style={{ borderCollapse: 'collapse' }}>
          <tbody>
            {Object.entries(data).map(([k, v], i) => (
              <tr key={k} className={i % 2 ? 'bg-[#FAFAF8]' : ''}>
                <td className="px-3 py-2 text-xs font-semibold text-[#6E6A63] w-1/3" style={{ borderBottom: '1px solid #EBE7DF' }}>
                  {k.replace(/_/g, ' ')}
                </td>
                <td className="px-3 py-2 text-[#1A1A18]" style={{ borderBottom: '1px solid #EBE7DF' }}>
                  {typeof v === 'number' ? v.toLocaleString() : String(v ?? '')}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }

  return null;
}
