import {
  DEFINITIVE_METHODOLOGY_URI,
  DEFINITIVE_METHODOLOGY_VERSION,
  DEFINITIVE_SPEC_URI,
  DEFINITIVE_SPEC_VERSION,
} from '../constants/definitive.js';

export const DEFINITIVE_CONFORMANCE_MODEL_RUNTIME_CASE_COUNT = 202;
export const DEFINITIVE_CONFORMANCE_DEAL_ROUTE_CASE_COUNT = 60;
export const DEFINITIVE_CONFORMANCE_PROMPT_META_CASE_COUNT = 104;
export const DEFINITIVE_CONFORMANCE_ROUTE_TRIGGER_CASE_COUNT = 30;
export const DEFINITIVE_CONFORMANCE_MODEL_STACK_CASE_COUNT = 33;
export const DEFINITIVE_CONFORMANCE_DEAL_OS_ARTIFACT_CASE_COUNT = 43;
export const DEFINITIVE_CONFORMANCE_TOTAL_CASE_COUNT =
  DEFINITIVE_CONFORMANCE_MODEL_RUNTIME_CASE_COUNT +
  DEFINITIVE_CONFORMANCE_DEAL_ROUTE_CASE_COUNT +
  DEFINITIVE_CONFORMANCE_PROMPT_META_CASE_COUNT +
  DEFINITIVE_CONFORMANCE_ROUTE_TRIGGER_CASE_COUNT +
  DEFINITIVE_CONFORMANCE_MODEL_STACK_CASE_COUNT +
  DEFINITIVE_CONFORMANCE_DEAL_OS_ARTIFACT_CASE_COUNT;

export const DEFINITIVE_CONFORMANCE_MODEL_RUNTIME_CATEGORIES = [
  'valuation',
  'normalization',
  'working_capital',
  'qoe_lite',
  'tax_structure',
  'real_estate_mechanics',
  'real_estate_gap_closure',
  'agreement_economics',
  'connected_tax',
  'tax_allocation',
  'credit_mechanics',
  'ip_mechanics',
  'dscr_stress',
  'sources_uses',
  'lbo',
  'hsr_triage',
  'legal_halt_scan',
  'earnout',
  'ppa',
  'rollover',
  'structure_analysis',
  'buyer_fit',
  'market_context',
  'sensitivity',
  'deal_comparison',
  'covenant_compliance',
  'pmi_value_creation',
  'deal_kill_probability',
  'timeline',
  'deal_scoring',
  'cap_table',
  'dcf_refusal',
  'deal_mechanics_route_map',
  'deal_mechanics_readiness',
  'authority_seed_plan',
  'substrate_architecture',
  'pass_through_boundary',
  'prompt_meta_behavior',
  'route_trigger_behavior',
  'model_stack_behavior',
  'deal_os_artifact_behavior',
] as const;

export function buildDefinitiveConformanceStatus() {
  return {
    suite: 'DEFINITIVE.conformance.v1',
    status: 'started',
    specVersion: DEFINITIVE_SPEC_VERSION,
    specUri: DEFINITIVE_SPEC_URI,
    methodologyVersion: DEFINITIVE_METHODOLOGY_VERSION,
    methodologyUri: DEFINITIVE_METHODOLOGY_URI,
    cases: {
      modelRuntime: DEFINITIVE_CONFORMANCE_MODEL_RUNTIME_CASE_COUNT,
      dealMechanicsRoute: DEFINITIVE_CONFORMANCE_DEAL_ROUTE_CASE_COUNT,
      promptMeta: DEFINITIVE_CONFORMANCE_PROMPT_META_CASE_COUNT,
      routeTrigger: DEFINITIVE_CONFORMANCE_ROUTE_TRIGGER_CASE_COUNT,
      modelStack: DEFINITIVE_CONFORMANCE_MODEL_STACK_CASE_COUNT,
      dealOsArtifact: DEFINITIVE_CONFORMANCE_DEAL_OS_ARTIFACT_CASE_COUNT,
      total: DEFINITIVE_CONFORMANCE_TOTAL_CASE_COUNT,
    },
    categories: DEFINITIVE_CONFORMANCE_MODEL_RUNTIME_CATEGORIES,
    assertions: [
      'version pins',
      'methodology pins',
      'output hash shape',
      'deterministic outputs',
      'nested deterministic outputs',
      'missing-input behavior',
      'refusal states',
      'Yulia prompt/meta boundaries',
      'surface guidance consistency',
      'Authority Register seed-plan coverage',
      'Authority Register staged migration seed coverage',
      'Authority Register staged seed coverage above 220 rows',
      'bankruptcy procedure and cramdown case-law anchors',
      'deferred-payment tax forms and real estate/UCC source anchors',
      'terminal substrate architecture primitives',
      'terminal substrate schema registry contracts',
      'CompletenessSpec definition-of-done contract',
      'Deal OS non-rejection agent lifecycle',
      'Deal OS iterative work surfaces and portable agent handoffs',
      'agent discoverability layers and marketplace metadata doctrine',
      'MCP server-card and well-known discovery metadata',
      'enterprise allow-list registry templates',
      'registry submission package coverage',
      'The Diligence Standard publication doctrine',
      'G28/G29/G30 trigger thresholds',
      'compose_model_stack payload behavior',
      'iterative Deal OS artifact schemas',
      'portable agent take-back artifacts',
      'document/data-room/IOI/LOI/negotiation/close/PMI boundaries',
      'resume/lifecycle/data-room/Studio/close/PMI iterative agent loop behavior',
      'package verification/finalization/reopen behavior',
      'structure permutation and best-vehicle computation boundaries',
      'partial ingest/update/diff/clone edge behavior',
      'package mismatch detection and close/funds-flow blocker behavior',
      'TypeScript and Python reference implementation smoke coverage',
    ],
    command: 'npm run test:definitive-conformance',
    authenticatedRouteSmoke: {
      status: 'expanded',
      command: 'npm run test:definitive-auth-route',
      fixture: 'DB fixture + JWT bearer token + live API server',
      assertions: [
        'public MCP server-card route is discoverable without JWT',
        'public MCP well-known manifest separates discovery from bearer execution',
        'public registry package and enterprise allow-list templates are live routes',
        'public schema, runbook, and model-catalog routes expose portable agent contracts',
        'protected endpoints reject missing JWT',
        'tool inventory is available with JWT',
        'THE LINE inventory is available with JWT',
        'corpus observation types publish structured-only rules',
        'corpus rights can be read and granted with JWT',
        'corpus observations strip identifiers and raw text before storage',
        'unsupported spec versions refuse before execution',
        'THE LINE returns human-approval refusal envelopes with JWT',
        'THE LINE returns counsel-review refusal envelopes with JWT',
        'THE LINE returns enterprise-scope refusal envelopes with JWT',
        'compose_model_stack returns mandate chain and G28/G29/G30 route map',
        'audit packet retrieval returns pinned reproducibility payloads',
        'Studio export audit packet routes return pinned export payloads',
        'staged agency action routes expose and cancel confirmation holds',
      ],
    },
    entitlementSmoke: {
      status: 'started',
      command: 'npm run test:definitive-entitlements',
      fixture: 'DB fixtures with TEST_MODE / DEV_NO_PAYWALL disabled inside the test process',
      assertions: [
        'Pro plan resolves without local dev entitlement bypass',
        'Pro API access is allowed before allowance exhaustion',
        'Pro API access returns credit_budget_required after allowance exhaustion',
        'Free API access returns enterprise_scope_required for MCP/API scope',
      ],
    },
    referenceImplementationSmoke: {
      status: 'started',
      command: 'npm run test:definitive-reference && npm run test:definitive-reference-python',
      fixture: 'DB-free cloneable TypeScript and Python reference packages sharing one JSON fixture set',
      casesPerRuntime: 4,
      assertions: [
        'reference packages execute without app shell, database, JWT, MCP server, or private services',
        'M109 working-capital peg computes deterministic normalized NWC',
        'M139 Section 1060 allocation computes residual-method classes from user-supplied values',
        'M199 FIRPTA withholding computes the residence withholding ladder',
        'M206 indemnification ladder computes cap, basket, and recoverable-loss math',
        'outputs include spec pins, methodology pins, sample authority refs, input hashes, output hashes, and THE LINE boundaries',
        'sample authority refs remain fixture-only and do not expose production Authority Register data',
      ],
    },
    nextTarget: 750,
  };
}
