/**
 * Export Service — Generate PDF, DOCX, and XLSX from deliverable content.
 *
 * PDF: pdfkit (lightweight, no browser dependency)
 * DOCX: docx library
 * XLSX: ExcelJS (formulas supported)
 */
import PDFDocument from 'pdfkit';
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Table, TableRow, TableCell, WidthType, BorderStyle,
  AlignmentType,
} from 'docx';
import ExcelJS from 'exceljs';
import { Readable } from 'stream';

// ─── PDF Export ──────────────────────────────────────────────

export async function exportToPDF(
  content: Record<string, any>,
  title: string,
  options?: { watermark?: string },
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
      info: {
        Title: title,
        Author: 'smbx.ai',
        Creator: 'SMBX Export Engine',
      },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(8).fillColor('#A9A49C')
      .text(`Generated by smbx.ai — ${new Date().toLocaleDateString()}`, { align: 'right' });
    doc.moveDown(0.5);

    // Title
    doc.fontSize(22).fillColor('#1A1A18').font('Helvetica-Bold')
      .text(title);
    doc.moveDown(0.3);
    doc.strokeColor('#BA3C60').lineWidth(2)
      .moveTo(60, doc.y).lineTo(552, doc.y).stroke();
    doc.moveDown(1);

    // Render content
    if (content.markdown) {
      renderMarkdownToPDF(doc, content.markdown);
    } else if (content.sections) {
      for (const section of content.sections) {
        renderSectionToPDF(doc, section);
      }
    } else {
      // Key-value pairs
      for (const [key, value] of Object.entries(content)) {
        if (key === 'type' || key === 'generated_at') continue;
        doc.fontSize(9).fillColor('#6E6A63').font('Helvetica-Bold')
          .text(key.replace(/_/g, ' ').toUpperCase());
        doc.fontSize(11).fillColor('#1A1A18').font('Helvetica')
          .text(String(value));
        doc.moveDown(0.5);
      }
    }

    // Watermark on each page
    if (options?.watermark) {
      const pages = doc.bufferedPageRange();
      for (let i = pages.start; i < pages.start + pages.count; i++) {
        doc.switchToPage(i);
        doc.save();
        doc.translate(306, 396);
        doc.rotate(-45);
        doc.fontSize(48).fillColor('#E8E4DC').fillOpacity(0.3)
          .text(options.watermark, -200, -20, { align: 'center', width: 400 });
        doc.restore();
      }
    }

    // Footer
    doc.fontSize(7).fillColor('#C5C0B6')
      .text('Confidential — Prepared by smbx.ai', 60, doc.page.height - 40, {
        align: 'center',
        width: 492,
      });

    doc.end();
  });
}

function renderMarkdownToPDF(doc: InstanceType<typeof PDFDocument>, markdown: string) {
  const lines = markdown.split('\n');

  for (const line of lines) {
    // Headings
    if (line.startsWith('## ')) {
      doc.moveDown(0.8);
      doc.fontSize(16).fillColor('#1A1A18').font('Helvetica-Bold')
        .text(line.replace(/^## /, '').replace(/\*\*/g, ''));
      doc.moveDown(0.3);
    } else if (line.startsWith('### ')) {
      doc.moveDown(0.5);
      doc.fontSize(13).fillColor('#3D3B37').font('Helvetica-Bold')
        .text(line.replace(/^### /, '').replace(/\*\*/g, ''));
      doc.moveDown(0.2);
    } else if (line.startsWith('# ')) {
      doc.moveDown(0.5);
      doc.fontSize(18).fillColor('#1A1A18').font('Helvetica-Bold')
        .text(line.replace(/^# /, '').replace(/\*\*/g, ''));
      doc.moveDown(0.3);
    } else if (line.startsWith('- [ ] ')) {
      // Checkbox items
      doc.fontSize(10).fillColor('#1A1A18').font('Helvetica')
        .text(`\u2610 ${line.replace(/^- \[ \] /, '')}`, { indent: 15 });
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      // Bullet points
      doc.fontSize(10).fillColor('#1A1A18').font('Helvetica')
        .text(`\u2022 ${line.replace(/^[-*] /, '').replace(/\*\*/g, '')}`, { indent: 15 });
    } else if (line.startsWith('---') || line.startsWith('***')) {
      doc.moveDown(0.3);
      doc.strokeColor('#DDD9D1').lineWidth(0.5)
        .moveTo(60, doc.y).lineTo(552, doc.y).stroke();
      doc.moveDown(0.3);
    } else if (line.trim() === '') {
      doc.moveDown(0.3);
    } else {
      // Regular text — handle bold markers
      const text = line.replace(/\*\*(.+?)\*\*/g, '$1');
      doc.fontSize(10).fillColor('#3D3B37').font('Helvetica')
        .text(text, { lineGap: 3 });
    }

    // Page break if near bottom
    if (doc.y > doc.page.height - 100) {
      doc.addPage();
    }
  }
}

function renderSectionToPDF(doc: InstanceType<typeof PDFDocument>, section: any) {
  doc.moveDown(0.5);
  doc.fontSize(14).fillColor('#1A1A18').font('Helvetica-Bold')
    .text(section.title);
  doc.moveDown(0.3);

  if (typeof section.content === 'string') {
    doc.fontSize(10).fillColor('#3D3B37').font('Helvetica')
      .text(section.content, { lineGap: 3 });
  } else if (section.items) {
    for (const item of section.items) {
      doc.fontSize(10).fillColor('#3D3B37').font('Helvetica')
        .text(`\u2022 ${item}`, { indent: 15 });
    }
  }
  doc.moveDown(0.5);
}

// ─── DOCX Export ─────────────────────────────────────────────

export async function exportToDOCX(
  content: Record<string, any>,
  title: string,
): Promise<Buffer> {
  const children: (Paragraph | Table)[] = [];

  // Title
  children.push(new Paragraph({
    text: title,
    heading: HeadingLevel.TITLE,
    spacing: { after: 200 },
  }));

  // Meta
  children.push(new Paragraph({
    children: [
      new TextRun({ text: `Generated by smbx.ai on ${new Date().toLocaleDateString()}`, size: 16, color: 'A9A49C' }),
    ],
    spacing: { after: 400 },
  }));

  if (content.markdown) {
    const lines = content.markdown.split('\n');
    for (const line of lines) {
      if (line.startsWith('## ')) {
        children.push(new Paragraph({
          text: line.replace(/^## /, '').replace(/\*\*/g, ''),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 },
        }));
      } else if (line.startsWith('### ')) {
        children.push(new Paragraph({
          text: line.replace(/^### /, '').replace(/\*\*/g, ''),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 100 },
        }));
      } else if (line.startsWith('# ')) {
        children.push(new Paragraph({
          text: line.replace(/^# /, '').replace(/\*\*/g, ''),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }));
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        children.push(new Paragraph({
          text: line.replace(/^[-*] /, '').replace(/\*\*/g, ''),
          bullet: { level: 0 },
        }));
      } else if (line.trim() === '') {
        children.push(new Paragraph({ text: '' }));
      } else {
        children.push(new Paragraph({
          children: parseTextRuns(line),
          spacing: { after: 80 },
        }));
      }
    }
  } else if (content.sections) {
    for (const section of content.sections) {
      children.push(new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }));
      if (typeof section.content === 'string') {
        children.push(new Paragraph({
          text: section.content,
          spacing: { after: 200 },
        }));
      }
    }
  }

  const doc = new Document({
    sections: [{ children }],
    creator: 'smbx.ai',
    title,
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

function parseTextRuns(line: string): TextRun[] {
  const runs: TextRun[] = [];
  const parts = line.split(/(\*\*.*?\*\*)/);
  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true }));
    } else {
      runs.push(new TextRun({ text: part }));
    }
  }
  return runs;
}

// ─── XLSX Export ──────────────────────────────────────────────

export async function exportToXLSX(
  content: Record<string, any>,
  title: string,
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'smbx.ai';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(title.substring(0, 31));

  // Title row
  sheet.mergeCells('A1:F1');
  const titleCell = sheet.getCell('A1');
  titleCell.value = title;
  titleCell.font = { size: 16, bold: true, color: { argb: 'FF1A1A18' } };
  titleCell.alignment = { vertical: 'middle' };
  sheet.getRow(1).height = 30;

  // Meta row
  sheet.mergeCells('A2:F2');
  const metaCell = sheet.getCell('A2');
  metaCell.value = `Generated by smbx.ai — ${new Date().toLocaleDateString()}`;
  metaCell.font = { size: 9, color: { argb: 'FFA9A49C' } };

  let currentRow = 4;

  // If content has tabular data, render as proper spreadsheet
  if (content.sections) {
    for (const section of content.sections) {
      // Section header
      const headerCell = sheet.getCell(`A${currentRow}`);
      headerCell.value = section.title;
      headerCell.font = { size: 12, bold: true, color: { argb: 'FF1A1A18' } };
      currentRow++;

      if (section.table && Array.isArray(section.table)) {
        const headers = Object.keys(section.table[0]);
        // Column headers
        headers.forEach((h, i) => {
          const cell = sheet.getCell(currentRow, i + 1);
          cell.value = h.replace(/_/g, ' ').toUpperCase();
          cell.font = { size: 9, bold: true, color: { argb: 'FF3D3B37' } };
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F0EA' } };
          cell.border = { bottom: { style: 'thin', color: { argb: 'FFDDD9D1' } } };
        });
        currentRow++;

        // Data rows
        for (const row of section.table) {
          headers.forEach((h, i) => {
            const cell = sheet.getCell(currentRow, i + 1);
            cell.value = row[h];
            if (typeof row[h] === 'number') {
              cell.numFmt = '#,##0';
            }
          });
          currentRow++;
        }
        currentRow++;
      } else if (typeof section.content === 'string') {
        const cell = sheet.getCell(`A${currentRow}`);
        cell.value = section.content;
        cell.alignment = { wrapText: true };
        currentRow += 2;
      }
    }
  } else {
    // Key-value pairs
    for (const [key, value] of Object.entries(content)) {
      if (key === 'type' || key === 'generated_at' || key === 'markdown') continue;
      sheet.getCell(`A${currentRow}`).value = key.replace(/_/g, ' ');
      sheet.getCell(`A${currentRow}`).font = { bold: true, size: 10 };
      sheet.getCell(`B${currentRow}`).value = typeof value === 'object' ? JSON.stringify(value) : value;
      currentRow++;
    }
  }

  // Auto-width columns
  sheet.columns.forEach(col => {
    col.width = Math.max(col.width || 12, 15);
  });

  return Buffer.from(await workbook.xlsx.writeBuffer());
}

// ─── Signature-Ready LOI PDF ─────────────────────────────────

export async function exportLOIToPDF(
  content: Record<string, any>,
  title: string,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 72, bottom: 72, left: 72, right: 72 },
      info: {
        Title: title,
        Author: 'smbx.ai',
        Creator: 'SMBX Export Engine',
      },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = 612 - 144; // LETTER width minus margins

    // Date
    doc.fontSize(10).fillColor('#3D3B37').font('Helvetica')
      .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), { align: 'right' });
    doc.moveDown(2);

    // Title
    doc.fontSize(18).fillColor('#1A1A18').font('Helvetica-Bold')
      .text(title, { align: 'center' });
    doc.moveDown(0.3);
    doc.strokeColor('#BA3C60').lineWidth(1.5)
      .moveTo(72, doc.y).lineTo(540, doc.y).stroke();
    doc.moveDown(1.5);

    // Parties section
    if (content.buyer_name || content.seller_name) {
      doc.fontSize(10).fillColor('#3D3B37').font('Helvetica');
      if (content.buyer_name) {
        doc.text(`Buyer: ${content.buyer_name}`);
      }
      if (content.seller_name) {
        doc.text(`Seller: ${content.seller_name}`);
      }
      if (content.business_name) {
        doc.text(`Business: ${content.business_name}`);
      }
      if (content.purchase_price) {
        doc.text(`Purchase Price: ${content.purchase_price}`);
      }
      doc.moveDown(1);
    }

    // LOI body content
    if (content.markdown) {
      renderMarkdownToPDF(doc, content.markdown);
    } else if (content.sections) {
      for (const section of content.sections) {
        renderSectionToPDF(doc, section);
      }
    } else {
      // Render any text content
      for (const [key, value] of Object.entries(content)) {
        if (['type', 'generated_at', 'buyer_name', 'seller_name', 'business_name', 'purchase_price'].includes(key)) continue;
        if (typeof value === 'string' && value.length > 0) {
          doc.fontSize(10).fillColor('#3D3B37').font('Helvetica')
            .text(String(value), { lineGap: 3 });
          doc.moveDown(0.5);
        }
      }
    }

    // Page break if needed for signatures
    if (doc.y > doc.page.height - 280) {
      doc.addPage();
    }

    // Signature blocks
    doc.moveDown(2);
    doc.strokeColor('#DDD9D1').lineWidth(0.5)
      .moveTo(72, doc.y).lineTo(540, doc.y).stroke();
    doc.moveDown(1.5);

    doc.fontSize(12).fillColor('#1A1A18').font('Helvetica-Bold')
      .text('AGREED AND ACCEPTED:');
    doc.moveDown(1.5);

    // Buyer signature
    doc.fontSize(10).fillColor('#3D3B37').font('Helvetica-Bold')
      .text('BUYER:');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica')
      .text(content.buyer_name || '____________________________');
    doc.moveDown(1.5);

    doc.strokeColor('#1A1A18').lineWidth(0.5)
      .moveTo(72, doc.y).lineTo(300, doc.y).stroke();
    doc.moveDown(0.2);
    doc.fontSize(8).fillColor('#6E6A63')
      .text('Signature');
    doc.moveDown(0.8);

    doc.strokeColor('#1A1A18').lineWidth(0.5)
      .moveTo(72, doc.y).lineTo(300, doc.y).stroke();
    doc.moveDown(0.2);
    doc.fontSize(8).fillColor('#6E6A63')
      .text('Printed Name                                                        Date');
    doc.moveDown(1.5);

    // Seller signature
    doc.fontSize(10).fillColor('#3D3B37').font('Helvetica-Bold')
      .text('SELLER:');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica')
      .text(content.seller_name || '____________________________');
    doc.moveDown(1.5);

    doc.strokeColor('#1A1A18').lineWidth(0.5)
      .moveTo(72, doc.y).lineTo(300, doc.y).stroke();
    doc.moveDown(0.2);
    doc.fontSize(8).fillColor('#6E6A63')
      .text('Signature');
    doc.moveDown(0.8);

    doc.strokeColor('#1A1A18').lineWidth(0.5)
      .moveTo(72, doc.y).lineTo(300, doc.y).stroke();
    doc.moveDown(0.2);
    doc.fontSize(8).fillColor('#6E6A63')
      .text('Printed Name                                                        Date');

    // Footer
    doc.fontSize(7).fillColor('#C5C0B6')
      .text('Confidential — Prepared by smbx.ai', 72, doc.page.height - 40, {
        align: 'center',
        width: pageWidth,
      });

    doc.end();
  });
}
