import { createHash } from 'crypto';
import type { League } from '../constants/v19Leagues.js';

export type V19ModelPhase = 'tier0' | 'phase2' | 'phase3';

export interface RegisteredModel {
  modelId: string;
  version: string;
  name: string;
  phase: V19ModelPhase;
  description: string;
  requiredInputs: string[];
  citationTags: string[];
  leagueFloor?: League;
  leagueCeiling?: League;
}

export interface RegisteredModelRecord extends RegisteredModel {
  hash: string;
}

const MODEL_ID_ALIASES: Record<string, string> = {
  'v19.sde.recast': 'MODEL.VAL.SDE.v1',
  'v19.ebitda.adjusted': 'MODEL.VAL.EBITDA.v1',
  'v19.valuation.multiple': 'MODEL.VAL.TRIANGULATION.v1',
  'v19.sba.bankability': 'MODEL.LBO.SBA.v1',
  'v19.dscr': 'MODEL.DSCR.STRESS.v1',
  'v19.qoe.lite': 'MODEL.QOE.LITE.v1',
  'v19.working_capital.peg': 'MODEL.STRUCT.NWC.PEG.v1',
  'v19.tax.structure': 'MODEL.TAX.STRUCTURE.v1',
  'v19.legal.haltscan': 'MODEL.LEGAL.HALTSCAN.v1',
  'v19.buyer.fit': 'MODEL.BUYER.FIT.v1',
  'v19.deal.score': 'MODEL.DEAL.SCORE.v1',
  'v19.market.context': 'MODEL.MARKET.CONTEXT.v1',
  'v19.sensitivity.matrix': 'MODEL.SENSITIVITY.MATRIX.v1',
  'v19.deal.comparison': 'MODEL.DEAL.COMPARISON.v1',
  'v19.lbo.lite': 'MODEL.LBO.LMM.v1',
  'v19.cap_table.dilution': 'MODEL.CAPTABLE.DILUTION.v1',
  'v19.earnout.ev': 'MODEL.STRUCT.EARNOUT.MC.v1',
  'v19.covenant.compliance': 'MODEL.COVENANT.COMPLIANCE.v1',
  'v19.dcf.simple': 'MODEL.VAL.DCF.TWOSTAGE.v1',
  'v19.pmi.value_creation': 'MODEL.PMI.VALUE.CREATION.v1',
};

const V19_MODEL_CATALOG: RegisteredModel[] = [
  {
    modelId: 'v19.sde.recast',
    version: '1.0.0',
    name: 'SDE Recast',
    phase: 'tier0',
    description: 'Normalizes owner-operated earnings using documented add-backs and compensation adjustments.',
    requiredInputs: ['revenue_cents', 'net_income_cents', 'owner_comp_cents', 'add_backs_cents'],
    citationTags: ['[Pepperdine PCAP 2025]'],
    leagueFloor: 'L1',
    leagueCeiling: 'L3',
  },
  {
    modelId: 'v19.ebitda.adjusted',
    version: '1.0.0',
    name: 'Adjusted EBITDA',
    phase: 'tier0',
    description: 'Normalizes EBITDA for lower-middle-market and larger deals with evidence-tagged adjustments.',
    requiredInputs: ['ebitda_cents', 'adjustments_cents', 'revenue_cents'],
    citationTags: ['[Damodaran 2026]', '[Kroll 2024]'],
    leagueFloor: 'L3',
    leagueCeiling: 'L10',
  },
  {
    modelId: 'v19.valuation.multiple',
    version: '1.0.0',
    name: 'Multiple Valuation',
    phase: 'tier0',
    description: 'Applies league-aware SDE or EBITDA multiple ranges and risk adjustments to normalized earnings.',
    requiredInputs: ['normalized_earnings_cents', 'base_multiple', 'league', 'risk_adjustments'],
    citationTags: ['[Damodaran 2026]', '[Pepperdine PCAP 2025]'],
    leagueFloor: 'L1',
    leagueCeiling: 'L10',
  },
  {
    modelId: 'v19.sba.bankability',
    version: '1.0.0',
    name: 'SBA Bankability',
    phase: 'tier0',
    description: 'Checks SBA acquisition debt capacity, equity injection, citizenship, seller-note standby, and DSCR.',
    requiredInputs: ['purchase_price_cents', 'cash_flow_cents', 'buyer_equity_cents', 'seller_note_cents'],
    citationTags: ['[SBA SOP 50 10 8]', '[FRED:DPRIME]'],
    leagueFloor: 'L1',
    leagueCeiling: 'L3',
  },
  {
    modelId: 'v19.dscr',
    version: '1.0.0',
    name: 'Debt Service Coverage',
    phase: 'tier0',
    description: 'Computes DSCR under SBA and conventional debt assumptions with lender-threshold checks.',
    requiredInputs: ['cash_flow_cents', 'annual_debt_service_cents', 'loan_type'],
    citationTags: ['[SBA SOP 50 10 8]'],
  },
  {
    modelId: 'v19.qoe.lite',
    version: '1.0.0',
    name: 'QoE Lite',
    phase: 'tier0',
    description: 'Scores earnings quality, add-back defensibility, working-capital proof, and data-room gaps.',
    requiredInputs: ['financial_facts', 'adjustments', 'data_room_files'],
    citationTags: ['[ABA 2025]', '[SRS 2025]'],
  },
  {
    modelId: 'v19.working_capital.peg',
    version: '1.0.0',
    name: 'Working Capital Peg',
    phase: 'tier0',
    description: 'Builds a trailing-period NWC peg and flags deal-structure language for counsel review.',
    requiredInputs: ['monthly_nwc_cents', 'seasonality_notes', 'closing_balance_cents'],
    citationTags: ['[ABA 2025]', '[SRS 2025]'],
  },
  {
    modelId: 'MODEL.SOURCES.USES.v1',
    version: 'v1',
    name: 'Sources and Uses',
    phase: 'tier0',
    description: 'Balances funding sources against purchase price, fees, rollover, and working-capital uses.',
    requiredInputs: ['sources_cents', 'uses_cents'],
    citationTags: [],
  },
  {
    modelId: 'MODEL.HSR.TRIAGE.v1',
    version: 'v1',
    name: 'HSR Triage',
    phase: 'tier0',
    description: 'Checks transaction size against current HSR thresholds and flags filing-tier review.',
    requiredInputs: ['enterprise_value_cents'],
    citationTags: ['[FTC 2026 HSR - Size of Transaction]', '[FTC 2026 HSR - Auto-Reportable]'],
  },
  {
    modelId: 'v19.tax.structure',
    version: '1.0.0',
    name: 'Tax Structure Lens',
    phase: 'tier0',
    description: 'Issue-spots asset sale, stock sale, QSBS, rollover, bonus depreciation, SALT, and interest limitation paths.',
    requiredInputs: ['deal_type', 'entity_type', 'purchase_price_cents', 'rollover_pct', 'tax_facts'],
    citationTags: ['[OBBBA Sec. 70301]', '[OBBBA Sec. 70302]', '[OBBBA Sec. 70425]', '[OBBBA Sec. 70505]'],
  },
  {
    modelId: 'MODEL.STRUCT.PPA.v1',
    version: 'v1',
    name: 'Purchase Price Allocation',
    phase: 'tier0',
    description: 'Frames §1060 purchase-price allocation across asset classes for tax review.',
    requiredInputs: ['purchase_price_cents', 'asset_classes'],
    citationTags: ['[OBBBA Sec. 70301]', '[OBBBA Sec. 70302]'],
  },
  {
    modelId: 'MODEL.STRUCT.ROLLOVER.v1',
    version: 'v1',
    name: 'Rollover Structure',
    phase: 'tier0',
    description: 'Frames rollover percentage, tax pathway, and counsel-review flags.',
    requiredInputs: ['rollover_pct', 'entity_type', 'deal_type'],
    citationTags: ['[OBBBA Sec. 70505]'],
  },
  {
    modelId: 'MODEL.STRUCT.ANALYSIS.v1',
    version: 'v1',
    name: 'Structure Analysis',
    phase: 'tier0',
    description: 'Combines tax, legal, financing, and execution-structure facts into a decision-ready issue map.',
    requiredInputs: ['deal_type', 'structure_facts'],
    citationTags: ['[SBA SOP 50 10 8]', '[FTC 2026 HSR - Size of Transaction]'],
  },
  {
    modelId: 'MODEL.RE.FIRPTA.WITHHOLDING.v1',
    version: 'v1',
    name: 'FIRPTA Withholding',
    phase: 'tier0',
    description: 'Computes FIRPTA withholding rate, amount, residence exception path, and form timing from supplied transaction facts.',
    requiredInputs: ['amount_realized_cents', 'seller_foreign_person'],
    citationTags: ['[IRC 1445]', '[IRS Form 8288]', '[IRS Form 8288-A]'],
  },
  {
    modelId: 'MODEL.RE.1031.TIMING.v1',
    version: 'v1',
    name: '1031 Exchange Timing',
    phase: 'tier0',
    description: 'Computes 45-day identification and 180-day exchange deadlines plus boot/value-shortfall recognition floor.',
    requiredInputs: ['transfer_date', 'relinquished_property_value_cents', 'replacement_property_value_cents'],
    citationTags: ['[IRC 1031]'],
  },
  {
    modelId: 'MODEL.RE.RENT_ROLL.NORMALIZE.v1',
    version: 'v1',
    name: 'Rent Roll Normalization',
    phase: 'tier0',
    description: 'Normalizes rent roll into occupancy, WALT, rent, and tenant-concentration metrics.',
    requiredInputs: ['rent_roll'],
    citationTags: ['[Real Estate Industry Practice]'],
  },
  {
    modelId: 'MODEL.RE.CAM.TRUEUP.v1',
    version: 'v1',
    name: 'CAM Reconciliation True-Up',
    phase: 'tier0',
    description: 'Computes tenant pro-rata recoverable expense share and closing-date CAM true-up.',
    requiredInputs: ['recoverable_expenses_cents'],
    citationTags: ['[BOMA]', '[Real Estate Industry Practice]'],
  },
  {
    modelId: 'MODEL.LEGAL.INDEMNITY.LADDER.v1',
    version: 'v1',
    name: 'Indemnification Ladder',
    phase: 'tier0',
    description: 'Computes indemnity cap, basket, fundamental cap, scrape default, and carve-out framing from deal value and RWI facts.',
    requiredInputs: ['transaction_value_cents'],
    citationTags: ['[ABA Private Target Deal Points Study 2023]', '[ABA Model SPA]'],
  },
  {
    modelId: 'MODEL.LEGAL.ESCROW.HOLDBACK.v1',
    version: 'v1',
    name: 'Escrow and Holdback Sizing',
    phase: 'tier0',
    description: 'Computes general indemnity escrow, PPA escrow, special escrows, and aggregate holdback sizing.',
    requiredInputs: ['transaction_value_cents'],
    citationTags: ['[SRS Acquiom 2024]', '[SRS Acquiom 2025]', '[ABA Private Target Deal Points Study 2023]'],
  },
  {
    modelId: 'MODEL.TAX.TRANSACTION.MASTER.v1',
    version: 'v1',
    name: 'Transaction Tax Master Engine',
    phase: 'tier0',
    description: 'Integrates entity type, deal form, consideration mix, basis, tax rates, buyer basis, seller tax, after-tax proceeds, gross-up gap, and fired tax sub-models.',
    requiredInputs: ['seller_entity_type', 'deal_form', 'purchase_price_cents'],
    citationTags: ['[IRC 1001]', '[IRC 338]', '[IRC 336]', '[IRC 351]', '[IRC 368]', '[IRC 721]', '[IRC 1060]'],
  },
  {
    modelId: 'MODEL.TAX.GROSSUP.338_336.v1',
    version: 'v1',
    name: '338(h)(10) / 336(e) Gross-Up Math',
    phase: 'tier0',
    description: 'Computes seller tax delta, breakeven gross-up, buyer step-up PV benefit, and 336(e) 80%-within-12-month window flag.',
    requiredInputs: ['seller_tax_delta_cents', 'seller_marginal_tax_rate'],
    citationTags: ['[IRC 338(h)(10)]', '[IRC 336(e)]', '[Treas. Reg. 1.336-2]'],
  },
  {
    modelId: 'MODEL.TAX.BIG.1374.v1',
    version: 'v1',
    name: '1374 Built-In Gains Tax',
    phase: 'tier0',
    description: 'Computes NUBIG, five-year recognition-period status, recognized BIG tax base, and federal corporate-level tax.',
    requiredInputs: ['fmv_at_conversion_cents', 'basis_at_conversion_cents', 'conversion_date', 'sale_date', 'recognized_gain_cents'],
    citationTags: ['[IRC 1374]', '[PATH Act 2015]'],
  },
  {
    modelId: 'MODEL.TAX.TRANSACTION_COSTS.v1',
    version: 'v1',
    name: 'Transaction Cost Capitalization',
    phase: 'tier0',
    description: 'Classifies transaction costs under bright-line, inherently facilitative, success-based fee safe harbor, capitalization, deduction, and Section 195 amortization buckets.',
    requiredInputs: ['transaction_costs', 'bright_line_date'],
    citationTags: ['[IRC 195]', '[IRC 263]', '[Treas. Reg. 1.263(a)-5]', '[Rev. Proc. 2011-29]', '[INDOPCO]', '[Letter Ruling 202308010]'],
  },
  {
    modelId: 'MODEL.TAX.IMPUTED_INTEREST_OID.v1',
    version: 'v1',
    name: 'Imputed Interest / OID / 453A',
    phase: 'tier0',
    description: 'Computes AFR shortfall, imputed interest/OID floor, and Section 453A installment receivable threshold exposure.',
    requiredInputs: ['principal_cents', 'stated_interest_rate', 'afr_rate', 'term_months'],
    citationTags: ['[IRC 483]', '[IRC 1274]', '[IRC 1274A]', '[IRC 453A]'],
  },
  {
    modelId: 'MODEL.LEGAL.SURVIVAL.PERIODS.v1',
    version: 'v1',
    name: 'Survival Period Engine',
    phase: 'tier0',
    description: 'Computes general, fundamental, tax, and fraud survival period dates from closing date and RWI facts.',
    requiredInputs: ['closing_date'],
    citationTags: ['[SRS Acquiom 2024]', '[SRS Acquiom 2025]', '[ABA Private Target Deal Points Study 2023]'],
  },
  {
    modelId: 'MODEL.LEGAL.CLOSING_TRUEUP.SEQUENCE.v1',
    version: 'v1',
    name: 'Closing Statement True-Up Sequence',
    phase: 'tier0',
    description: 'Computes working-capital true-up economics and the actual statement, dispute notice, and negotiation timeline.',
    requiredInputs: ['closing_date', 'peg_cents', 'actual_nwc_cents'],
    citationTags: ['[SRS Acquiom Working Capital PPA Study]', '[ABA Private Target Deal Points Study 2023]'],
  },
  {
    modelId: 'MODEL.LEGAL.CONDITIONS.LOGIC.v1',
    version: 'v1',
    name: 'Conditions-to-Close Logic',
    phase: 'tier0',
    description: 'Computes condition-node satisfaction, waiver, open blockers, closing readiness, and professional-review flags.',
    requiredInputs: ['conditions'],
    citationTags: ['[ABA Model SPA]', '[HSR Act]', '[CFIUS regulations]'],
  },
  {
    modelId: 'MODEL.LEGAL.TERMINATION.FEES.v1',
    version: 'v1',
    name: 'Termination and Break Fee Economics',
    phase: 'tier0',
    description: 'Computes target break-up fee, go-shop discounted fee, reverse termination fee, and antitrust reverse fee from transaction value.',
    requiredInputs: ['transaction_value_cents'],
    citationTags: ['[Houlihan Lokey 2023 Transaction Termination Fee Study]', '[Fenwick 2023 ARBF analysis]', '[Brazen v. Bell Atlantic]', '[In re Topps]'],
  },
  {
    modelId: 'MODEL.TAX.1060.ALLOCATION.v1',
    version: 'v1',
    name: '1060 Seven-Class Allocation',
    phase: 'tier0',
    description: 'Allocates purchase price across Class I through VII using residual-method ordering and Form 8594-ready class output.',
    requiredInputs: ['purchase_price_cents', 'asset_classes'],
    citationTags: ['[IRC 1060]', '[Treas. Reg. 1.1060-1]', '[IRS Form 8594]'],
  },
  {
    modelId: 'MODEL.RE.SALE_LEASEBACK.ASC842.v1',
    version: 'v1',
    name: 'Sale-Leaseback / ASC 842 Mechanics',
    phase: 'tier0',
    description: 'Computes sale-leaseback cap rate, nominal rent burden, and ASC 842 finance-lease indicator flags from supplied facts.',
    requiredInputs: ['sale_price_cents', 'annual_rent_cents', 'lease_term_years'],
    citationTags: ['[ASC 842]', '[Real Estate Industry Practice]'],
  },
  {
    modelId: 'MODEL.RE.REIT.COMPLIANCE.v1',
    version: 'v1',
    name: 'REIT 75/75/90 Compliance Triad',
    phase: 'tier0',
    description: 'Checks REIT income, asset, and distribution percentages against 75/75/90 threshold mechanics.',
    requiredInputs: ['real_estate_income_cents', 'total_income_cents', 'real_estate_assets_cents', 'total_assets_cents', 'distributions_cents', 'taxable_income_cents'],
    citationTags: ['[IRC 856]', '[IRC 857]', '[IRC 858]', '[IRC 859]', '[IRC 860]'],
  },
  {
    modelId: 'MODEL.FINANCE.CONVERTIBLE_SAFE.v1',
    version: 'v1',
    name: 'Convertible / SAFE Conversion',
    phase: 'tier0',
    description: 'Computes conversion price and converted shares using priced-round price, discount, and valuation-cap mechanics.',
    requiredInputs: ['investment_cents', 'priced_round_share_price_cents'],
    citationTags: ['[YC SAFE]', '[Convertible Financing Market Practice]'],
  },
  {
    modelId: 'MODEL.FINANCE.ABL.BORROWING_BASE.v1',
    version: 'v1',
    name: 'ABL Borrowing Base',
    phase: 'tier0',
    description: 'Computes eligible A/R and inventory advance amounts, reserves, and net borrowing-base availability.',
    requiredInputs: ['eligible_ar_cents', 'eligible_inventory_cents'],
    citationTags: ['[ABL Market Practice]'],
  },
  {
    modelId: 'MODEL.FINANCE.MAKE_WHOLE_CALL.v1',
    version: 'v1',
    name: 'Make-Whole and Call Protection',
    phase: 'tier0',
    description: 'Computes a treasury-plus-spread make-whole amount and compares it to stated call-price economics.',
    requiredInputs: ['principal_cents', 'coupon_rate', 'treasury_rate', 'spread_bps', 'remaining_years'],
    citationTags: ['[Indenture Practice]'],
  },
  {
    modelId: 'MODEL.FINANCE.COVENANT_BASKETS.v1',
    version: 'v1',
    name: 'Covenant Basket Engine',
    phase: 'tier0',
    description: 'Computes fixed, grower, builder, ratio, used, and remaining basket capacity across credit-agreement baskets.',
    requiredInputs: ['baskets'],
    citationTags: ['[LSTA Model Provisions]', '[Credit Agreement Market Practice]'],
  },
  {
    modelId: 'MODEL.TAX.280G.PARACHUTE.v1',
    version: 'v1',
    name: '280G Golden Parachute',
    phase: 'tier0',
    description: 'Computes three-times-base trigger, excess parachute payment, 20 percent excise tax, lost deduction, and shareholder-cleansing threshold.',
    requiredInputs: ['base_amount_cents', 'parachute_payments_cents'],
    citationTags: ['[IRC 280G]', '[IRC 4999]'],
  },
  {
    modelId: 'MODEL.TAX.382.NOL_LIMIT.v1',
    version: 'v1',
    name: '382 NOL Limitation',
    phase: 'tier0',
    description: 'Computes annual Section 382 limitation as loss-corporation value times the long-term tax-exempt rate.',
    requiredInputs: ['loss_corporation_value_cents', 'long_term_tax_exempt_rate'],
    citationTags: ['[IRC 382(b)(1)]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.SOLVENCY.THREE_PRONG.v1',
    version: 'v1',
    name: 'Three-Prong Solvency',
    phase: 'tier0',
    description: 'Computes balance-sheet, cash-flow, and capital-adequacy prongs from user-supplied valuation and liquidity inputs.',
    requiredInputs: ['fair_value_assets_cents', 'liabilities_cents', 'projected_cash_flow_cents', 'debts_due_cents', 'available_capital_cents', 'required_capital_cents'],
    citationTags: ['[11 U.S.C. 548]', '[UVTA]', '[Tribune]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.363_SALE.v1',
    version: 'v1',
    name: '363 Asset Sale Mechanics',
    phase: 'tier0',
    description: 'Computes bid-protection economics, free-and-clear prongs, lien coverage, and credit-bid eligibility from supplied sale facts.',
    requiredInputs: ['purchase_price_cents', 'lien_amount_cents'],
    citationTags: ['[11 U.S.C. 363]', '[11 U.S.C. 365]', '[RadLAX]', '[Fisker]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.PLAN_FEASIBILITY.v1',
    version: 'v1',
    name: 'Plan Feasibility',
    phase: 'tier0',
    description: 'Computes forecast-period DSCR, liquidity-floor compliance, and downside cash-flow sensitivity for Chapter 11 plan feasibility.',
    requiredInputs: ['forecast_periods'],
    citationTags: ['[11 U.S.C. 1129(a)(11)]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.BIOC.v1',
    version: 'v1',
    name: 'Best-Interests-of-Creditors',
    phase: 'tier0',
    description: 'Compares per-class plan distributions against Chapter 7 liquidation distributions and flags shortfalls.',
    requiredInputs: ['creditor_classes'],
    citationTags: ['[11 U.S.C. 1129(a)(7)]', '[11 U.S.C. 726]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.APR_NEW_VALUE.v1',
    version: 'v1',
    name: 'Absolute Priority and New Value',
    phase: 'tier0',
    description: 'Computes impaired dissenting senior-class recovery, junior-value leakage, and a new-value scaffold for court/counsel review.',
    requiredInputs: ['classes'],
    citationTags: ['[11 U.S.C. 1129(b)(2)]', '[203 N. LaSalle]', '[Castleton Plaza]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.CRAMDOWN_RATE.v1',
    version: 'v1',
    name: 'Cramdown Interest Rate',
    phase: 'tier0',
    description: 'Computes Till formula and efficient-market framework outputs, with circuit support and court-rate handoff flags.',
    requiredInputs: ['base_rate', 'risk_premium'],
    citationTags: ['[Till]', '[MPM Silicones]', '[Texas Grand Prairie]', '[Topp]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.1111B_ELECTION.v1',
    version: 'v1',
    name: '1111(b) Election Trade-Off',
    phase: 'tier0',
    description: 'Computes no-election value, election NPV, aggregate face test, collateral NPV test, eligibility, and vote threshold flags.',
    requiredInputs: ['allowed_claim_cents', 'collateral_value_cents', 'plan_payment_stream_cents', 'discount_rate'],
    citationTags: ['[11 U.S.C. 1111(b)]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.CH7_WATERFALL.v1',
    version: 'v1',
    name: '726 Chapter 7 Waterfall',
    phase: 'tier0',
    description: 'Computes a priority-ranked liquidation distribution and recovery schedule under supplied claim classes.',
    requiredInputs: ['estate_value_cents', 'claims'],
    citationTags: ['[11 U.S.C. 507]', '[11 U.S.C. 726]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.DIP_SIZING.v1',
    version: 'v1',
    name: '364 DIP Sizing',
    phase: 'tier0',
    description: 'Computes required DIP commitment from 13-week need, minimum liquidity, opening cash, roll-up, carve-out, and new-money inputs.',
    requiredInputs: ['thirteen_week_cash_need_cents', 'minimum_liquidity_cents'],
    citationTags: ['[11 U.S.C. 364]', '[Collier 364.06]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.EXCHANGE_OFFER.v1',
    version: 'v1',
    name: 'Exchange Offer and Distressed-Debt Exchange',
    phase: 'tier0',
    description: 'Computes participation, holdout debt, exchange discount, CODI exposure, and minimum-participation satisfaction.',
    requiredInputs: ['outstanding_debt_cents', 'participating_debt_cents', 'new_security_value_cents'],
    citationTags: ['[Securities Act 3(a)(9)]', '[TIA 316(b)]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.FULCRUM_SECURITY.v1',
    version: 'v1',
    name: 'Fulcrum Security',
    phase: 'tier0',
    description: 'Applies enterprise value down the capital stack and identifies the fulcrum tranche at supplied EV.',
    requiredInputs: ['enterprise_value_cents', 'tranches'],
    citationTags: ['[Restructuring Market Practice]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.RSA_ECONOMICS.v1',
    version: 'v1',
    name: 'RSA Economics',
    phase: 'tier0',
    description: 'Computes class support thresholds, milestone status, termination-event count, fiduciary-out flag, and toggle type.',
    requiredInputs: ['classes'],
    citationTags: ['[11 U.S.C. 1125]', '[Indianapolis Downs]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.ABC_ARTICLE9.v1',
    version: 'v1',
    name: 'ABC and Article 9 Foreclosure Recovery',
    phase: 'tier0',
    description: 'Computes liquidation value after sale costs, Article 9 notice-floor compliance, and priority recovery waterfall.',
    requiredInputs: ['liquidation_value_cents', 'claims'],
    citationTags: ['[UCC 9-610]', '[UCC 9-611]', '[UCC 9-615]', '[State ABC Law]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.CLAIMS_TRADING.v1',
    version: 'v1',
    name: 'Claims Trading Recovery',
    phase: 'tier0',
    description: 'Computes expected recovery from post-default trading price or supplied recovery rate, gross profit, and estimated IRR.',
    requiredInputs: ['face_amount_cents', 'purchase_price_cents', 'time_to_recovery_years'],
    citationTags: ['[Moody\'s Ultimate Recovery Database]', '[FRBP 3001]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.SUBCHAPTER_V_ELIGIBILITY.v1',
    version: 'v1',
    name: 'Subchapter V Eligibility',
    phase: 'tier0',
    description: 'Checks supplied debt, commercial-activity, and public-issuer affiliate facts against the current Subchapter V threshold.',
    requiredInputs: ['aggregate_noncontingent_liquidated_debt_cents', 'engaged_in_commercial_activity'],
    citationTags: ['[11 U.S.C. 1181-1195]'],
  },
  {
    modelId: 'MODEL.RESTRUCTURING.CHAPTER22.RECIDIVISM.v1',
    version: 'v1',
    name: 'Chapter 22 Recidivism Score',
    phase: 'tier0',
    description: 'Scores post-emergence repeat-filing risk from exit leverage, liquidity runway, EBITDA growth, and prior bankruptcy count.',
    requiredInputs: ['exit_leverage', 'liquidity_months', 'ebitda_growth_pct'],
    citationTags: ['[LoPucki Bankruptcy Research Database]'],
  },
  {
    modelId: 'MODEL.SECONDARIES.LP_ECI.v1',
    version: 'v1',
    name: 'LP Secondary and ECI Withholding',
    phase: 'tier0',
    description: 'Computes 1446(f) default withholding, PSA requirement, tri-party transfer requirement, and tax specialist handoff flag.',
    requiredInputs: ['purchase_price_cents', 'seller_foreign_person'],
    citationTags: ['[IRC 1446(f)]', '[ILPA Guidance]'],
  },
  {
    modelId: 'MODEL.SECONDARIES.STRIP_SALE.v1',
    version: 'v1',
    name: 'Strip Sale Pricing',
    phase: 'tier0',
    description: 'Computes sold NAV, retained NAV, implied total value, and discount or premium to fund NAV.',
    requiredInputs: ['fund_nav_cents', 'strip_percentage', 'sale_price_cents'],
    citationTags: ['[Secondary Market Practice]'],
  },
  {
    modelId: 'MODEL.FINANCE.NAV_FACILITY.v1',
    version: 'v1',
    name: 'NAV Facility LTV',
    phase: 'tier0',
    description: 'Computes fund NAV LTV, cushion, required cushion, and lender-handoff flag.',
    requiredInputs: ['fund_nav_cents', 'loan_amount_cents'],
    citationTags: ['[NAV Facility Market Practice]'],
  },
  {
    modelId: 'MODEL.FINANCE.VENTURE_DEBT_WARRANT.v1',
    version: 'v1',
    name: 'Venture-Debt Warrant Coverage',
    phase: 'tier0',
    description: 'Computes warrant coverage amount, shares, intrinsic warrant value, simple interest, gross return, and estimated lender IRR.',
    requiredInputs: ['loan_amount_cents', 'warrant_coverage_pct', 'exercise_price_cents', 'fair_value_share_price_cents'],
    citationTags: ['[Venture Debt Market Practice]'],
  },
  {
    modelId: 'MODEL.RE.ASSET_ENTITY.ELECTION.v1',
    version: 'v1',
    name: 'RE-Heavy Asset-vs-Entity Election',
    phase: 'tier0',
    description: 'Computes real-estate percentage of EV, asset/entity basis paths, step-up, transfer tax, debt assumability, and lease treatment flags.',
    requiredInputs: ['enterprise_value_cents', 'real_property_value_cents'],
    citationTags: ['[IRC 1001]', '[IRC 1060]', '[IRC 197]'],
  },
  {
    modelId: 'MODEL.RE.OPBUS.BIFURCATION.v1',
    version: 'v1',
    name: 'RE / Operating Business Bifurcation',
    phase: 'tier0',
    description: 'Bifurcates enterprise value into NOI/cap-rate real estate value, operating-business residual, and Form 8594 Class V/VI/VII reconciliation.',
    requiredInputs: ['enterprise_value_cents', 'noi_cents', 'cap_rate'],
    citationTags: ['[Treas. Reg. 1.338-6]', '[IRS Form 8594]'],
  },
  {
    modelId: 'MODEL.RE.NOI.CAP_RATE_BRIDGE.v1',
    version: 'v1',
    name: 'NOI Normalization and Cap-Rate Bridge',
    phase: 'tier0',
    description: 'Computes normalized NOI, cap-rate value, implied cap rate, and pass-through market-rate dependency from supplied inputs.',
    requiredInputs: ['effective_gross_income_cents', 'operating_expenses_cents', 'cap_rate'],
    citationTags: ['[Appraisal Institute Practice]', '[Real Estate Industry Practice]'],
  },
  {
    modelId: 'MODEL.RE.LEASE_ABSTRACTION.v1',
    version: 'v1',
    name: 'Lease Abstraction Schema',
    phase: 'tier0',
    description: 'Normalizes supplied lease facts into WALT, rent, consent, option, exclusive-use, co-tenancy, and go-dark fields without legal interpretation.',
    requiredInputs: ['leases'],
    citationTags: ['[Lease Abstraction Industry Practice]'],
  },
  {
    modelId: 'MODEL.RE.PCA.RESERVES.v1',
    version: 'v1',
    name: 'PCA Reserve Modeling',
    phase: 'tier0',
    description: 'Structures pass-through PCA report items into immediate repair escrow and 1/3, 4/5, and 6/12-year reserve buckets.',
    requiredInputs: ['pca_items'],
    citationTags: ['[ASTM E2018]', '[Lender Practice]'],
  },
  {
    modelId: 'MODEL.RE.PROPERTY_ESCROW.HOLDBACK.v1',
    version: 'v1',
    name: 'Property-Level Escrow and Holdback Sizing',
    phase: 'tier0',
    description: 'Computes environmental, PCA, title, tenant, cost-to-cure, and other property-specific escrow buckets from supplied issue costs.',
    requiredInputs: ['issues'],
    citationTags: ['[ALTA Endorsements]', '[Real Estate Practice Norms]'],
  },
  {
    modelId: 'MODEL.RE.TITLE_SURVEY.CHECKLIST.v1',
    version: 'v1',
    name: 'Title and Survey Process Checklist',
    phase: 'tier0',
    description: 'Computes title/survey process status, Schedule B exception counts, endorsements, curative items, and closing-protection requirements.',
    requiredInputs: ['title_commitment_received', 'survey_received'],
    citationTags: ['[ALTA Forms]', '[State Title Statutes]'],
  },
  {
    modelId: 'MODEL.RE.FIRPTA.WITHHOLDING.V11.v1',
    version: 'v1',
    name: 'FIRPTA Withholding v1.1',
    phase: 'tier0',
    description: 'Computes FIRPTA withholding ladder, 8288 due date, 8288-B reduced certificate timing, and 1031 timing-gap flag.',
    requiredInputs: ['amount_realized_cents', 'seller_foreign_person'],
    citationTags: ['[IRC 897]', '[IRC 1445]', '[IRS Form 8288]', '[IRS Form 8288-A]', '[IRS Form 8288-B]'],
  },
  {
    modelId: 'MODEL.IP.CHAIN_OF_TITLE.v1',
    version: 'v1',
    name: 'IP Chain-of-Title Verification',
    phase: 'tier0',
    description: 'Computes assignment-chain, recording, contributor-assignment, and ITU-assignment risk counts from supplied IP asset facts.',
    requiredInputs: ['assets'],
    citationTags: ['[35 U.S.C. 261]', '[Lanham Act 10]', '[17 U.S.C. 205]', '[Clorox v. Chemical Bank]'],
  },
  {
    modelId: 'MODEL.IP.ENCUMBRANCE_LIEN_SEARCH.v1',
    version: 'v1',
    name: 'IP Encumbrance and Lien Search',
    phase: 'tier0',
    description: 'Computes UCC, USPTO, and Copyright Office hit counts and release requirements from pass-through lien-search outputs.',
    requiredInputs: ['searches'],
    citationTags: ['[UCC Article 9]', '[17 U.S.C. 205]', '[In re Peregrine]', '[Rhone-Poulenc Agro v. DeKalb]'],
  },
  {
    modelId: 'MODEL.IP.REPRESENTATION_SET.v1',
    version: 'v1',
    name: 'Standard IP Representation Set',
    phase: 'tier0',
    description: 'Computes an industry-scaled IP representation and schedule set for counsel drafting without drafting clause language.',
    requiredInputs: ['deal_type', 'material_ip_categories'],
    citationTags: ['[ABA Model SPA IP Representations]'],
  },
  {
    modelId: 'MODEL.IP.LICENSE.DEPENDENCY.v1',
    version: 'v1',
    name: 'License In/Out Dependency Map',
    phase: 'tier0',
    description: 'Computes inbound/outbound license counts, annual royalty, change-of-control consent, termination, sublicensing, and dependency flags.',
    requiredInputs: ['licenses'],
    citationTags: ['[IP Licensing Industry Practice]'],
  },
  {
    modelId: 'MODEL.IP.SOURCE_CODE_ESCROW.v1',
    version: 'v1',
    name: 'Source-Code and IP Escrow Mechanics',
    phase: 'tier0',
    description: 'Computes release trigger count, deposit verification tier, build/run-test flags, and next deposit due date.',
    requiredInputs: ['release_triggers', 'deposit_verification_tier'],
    citationTags: ['[Escode]', '[Codekeeper]', '[Iron Mountain Escrow Templates]'],
  },
  {
    modelId: 'MODEL.IP.EMPLOYEE_ASSIGNMENT.VERIFICATION.v1',
    version: 'v1',
    name: 'Employee IP Assignment Verification',
    phase: 'tier0',
    description: 'Computes contributor assignment, work-for-hire, and state carve-out flags from supplied contributor records.',
    requiredInputs: ['contributors'],
    citationTags: ['[California Labor Code 2870]', '[State Employee-IP Statutes]'],
  },
  {
    modelId: 'MODEL.IP.OSS.EXPOSURE.v1',
    version: 'v1',
    name: 'OSS Exposure Diligence Process',
    phase: 'tier0',
    description: 'Classifies OSS components by license family and computes AGPL, strong-copyleft, indemnity, and remediation escrow flags.',
    requiredInputs: ['components'],
    citationTags: ['[GPL]', '[AGPL]', '[LGPL]', '[MIT]', '[Apache]', '[BSD]', '[Morgan Lewis OSS Guidance]', '[Nixon Peabody OSS Guidance]', '[Morse OSS Guidance]'],
  },
  {
    modelId: 'MODEL.IP.1060.ALLOCATION.v1',
    version: 'v1',
    name: 'IP-Specific 1060 Allocation',
    phase: 'tier0',
    description: 'Allocates IP-heavy purchase price across Class V tangible assets, Class VI IP intangibles, and Class VII goodwill/going concern.',
    requiredInputs: ['purchase_price_cents', 'tangible_assets_cents', 'ip_intangibles_cents'],
    citationTags: ['[IRC 1060]', '[Treas. Reg. 1.338-6(b)]', '[Treas. Reg. 1.1060-1]', '[IRS Form 8594]'],
  },
  {
    modelId: 'MODEL.IP.DOMAIN_TM.TRANSFER.v1',
    version: 'v1',
    name: 'Domain and Trademark Transfer Mechanics',
    phase: 'tier0',
    description: 'Computes domain auth-code, ICANN lock, USPTO assignment, state trademark, social-handle, and SSL transfer counts.',
    requiredInputs: ['transfer_assets'],
    citationTags: ['[ICANN Transfer Rules]', '[USPTO Form PTO-1594]'],
  },
  {
    modelId: 'v19.legal.haltscan',
    version: '1.0.0',
    name: 'Legal Halt Scan',
    phase: 'tier0',
    description: 'Routes regulated, consent-heavy, antitrust, CFIUS, transfer, and professional-signoff issues to human counsel.',
    requiredInputs: ['deal_type', 'industry', 'jurisdiction', 'enterprise_value_cents', 'legal_facts'],
    citationTags: ['[FTC 2026 HSR - Size of Transaction]', '[FTC 2026 HSR - Auto-Reportable]'],
  },
  {
    modelId: 'v19.buyer.fit',
    version: '1.0.0',
    name: 'Buyer Fit',
    phase: 'tier0',
    description: 'Scores buyer universe fit, financing practicality, strategic rationale, and execution risk.',
    requiredInputs: ['industry', 'location', 'deal_size_cents', 'buyer_thesis', 'operating_needs'],
    citationTags: ['[Pepperdine PCAP 2025]'],
  },
  {
    modelId: 'v19.deal.score',
    version: '1.0.0',
    name: 'Deal Score',
    phase: 'tier0',
    description: 'Combines fit, earnings quality, evidence burden, market demand, and execution risk into a board-ready score.',
    requiredInputs: ['fit_score', 'earnings_quality_score', 'evidence_score', 'risk_score'],
    citationTags: ['[Pepperdine PCAP 2025]', '[ABA 2025]'],
  },
  {
    modelId: 'v19.market.context',
    version: '1.0.0',
    name: 'Market Context',
    phase: 'tier0',
    description: 'Attaches live macro and spread data snapshots to valuation, financing, and market-read outputs.',
    requiredInputs: ['series_ids', 'as_of_date'],
    citationTags: ['[FRED:SOFR]', '[FRED:DGS10]', '[FRED:BAMLH0A0HYM2]', '[FRED:BAMLC0A0CM]', '[FRED:VIXCLS]'],
  },
  {
    modelId: 'v19.sensitivity.matrix',
    version: '1.0.0',
    name: 'Sensitivity Matrix',
    phase: 'tier0',
    description: 'Builds two-variable matrices for valuation, returns, debt capacity, and downside cases.',
    requiredInputs: ['base_case', 'x_axis', 'y_axis', 'output_metric'],
    citationTags: [],
  },
  {
    modelId: 'v19.deal.comparison',
    version: '1.0.0',
    name: 'Deal Comparison',
    phase: 'tier0',
    description: 'Normalizes multiple deals onto a common board with current, optimized, and risk-adjusted views.',
    requiredInputs: ['deal_ids', 'comparison_lens', 'assumption_scope'],
    citationTags: [],
  },
  {
    modelId: 'v19.lbo.lite',
    version: '1.0.0',
    name: 'LBO Lite',
    phase: 'phase2',
    description: 'Projects sources/uses, leverage, cash sweep, exit value, MOIC, and IRR for sponsor-style deals.',
    requiredInputs: ['purchase_price_cents', 'debt_cents', 'sponsor_equity_cents', 'entry_ebitda_cents', 'exit_multiple'],
    citationTags: ['[FRED:SOFR]', '[FRED:BAMLH0A0HYM2]'],
    leagueFloor: 'L3',
    leagueCeiling: 'L10',
  },
  {
    modelId: 'v19.cap_table.dilution',
    version: '1.0.0',
    name: 'Cap Table Dilution',
    phase: 'phase2',
    description: 'Models dilution, option pool, convertible securities, and exit waterfall economics.',
    requiredInputs: ['pre_money_cents', 'round_size_cents', 'option_pool_pct', 'security_terms'],
    citationTags: [],
  },
  {
    modelId: 'v19.earnout.ev',
    version: '1.0.0',
    name: 'Earnout Expected Value',
    phase: 'phase2',
    description: 'Calculates probability-weighted earnout value and negotiation sensitivity.',
    requiredInputs: ['earnout_targets', 'probabilities', 'discount_rate'],
    citationTags: ['[ABA 2025]', '[SRS 2025]'],
  },
  {
    modelId: 'v19.covenant.compliance',
    version: '1.0.0',
    name: 'Covenant Compliance',
    phase: 'phase2',
    description: 'Tracks leverage, FCCR, liquidity, and EBITDA definition compliance over the forecast.',
    requiredInputs: ['forecast_periods', 'covenant_terms', 'debt_schedule'],
    citationTags: ['[FRED:SOFR]', '[FRED:BAMLC0A0CM]'],
  },
  {
    modelId: 'v19.dcf.simple',
    version: '1.0.0',
    name: 'DCF Simple',
    phase: 'phase2',
    description: 'Builds a compact discounted cash-flow valuation with terminal value and discount-rate sensitivity.',
    requiredInputs: ['free_cash_flows_cents', 'discount_rate', 'terminal_growth_rate'],
    citationTags: ['[Damodaran 2026]', '[Kroll 2024]'],
  },
  {
    modelId: 'v19.pmi.value_creation',
    version: '1.0.0',
    name: 'PMI Value Creation',
    phase: 'phase3',
    description: 'Turns diligence findings into post-close milestones, value levers, ownership, and day-0 controls.',
    requiredInputs: ['deal_findings', 'integration_risks', 'value_levers'],
    citationTags: [],
  },
];

export function listRegisteredModels(): RegisteredModelRecord[] {
  return V19_MODEL_CATALOG.map(toCanonicalModel).map(withHash);
}

export function getRegisteredModel(modelId: string, version?: string): RegisteredModelRecord | null {
  const canonicalModelId = canonicalizeModelId(modelId);
  const canonicalVersion = canonicalizeModelVersion(version);
  const model = V19_MODEL_CATALOG
    .map(toCanonicalModel)
    .find(candidate =>
      candidate.modelId === canonicalModelId && (!canonicalVersion || candidate.version === canonicalVersion)
  );
  return model ? withHash(model) : null;
}

export function canonicalizeModelId(modelId: string): string {
  const trimmed = String(modelId || '').trim();
  return MODEL_ID_ALIASES[trimmed] || trimmed;
}

export async function ensureModelRegistrySeeded(): Promise<{ insertedOrUpdated: number }> {
  const { sql } = await import('../db.js');
  const models = listRegisteredModels();
  for (const model of models) {
    await sql`
      INSERT INTO model_registry (
        model_id, version, hash, change_log, test_status, hallucination_test_status
      )
      VALUES (
        ${model.modelId},
        ${model.version},
        ${model.hash},
        ${JSON.stringify({
          name: model.name,
          phase: model.phase,
          description: model.description,
          requiredInputs: model.requiredInputs,
          citationTags: model.citationTags,
          leagueFloor: model.leagueFloor ?? null,
          leagueCeiling: model.leagueCeiling ?? null,
        })},
        'cataloged',
        'citation-bound'
      )
      ON CONFLICT (model_id, version) DO UPDATE SET
        hash = EXCLUDED.hash,
        change_log = EXCLUDED.change_log,
        test_status = EXCLUDED.test_status,
        hallucination_test_status = EXCLUDED.hallucination_test_status,
        deprecated_at = NULL
    `;
  }
  return { insertedOrUpdated: models.length };
}

function withHash(model: RegisteredModel): RegisteredModelRecord {
  const hash = createHash('sha256')
    .update(JSON.stringify({
      modelId: model.modelId,
      version: model.version,
      name: model.name,
      phase: model.phase,
      description: model.description,
      requiredInputs: model.requiredInputs,
      citationTags: model.citationTags,
      leagueFloor: model.leagueFloor ?? null,
      leagueCeiling: model.leagueCeiling ?? null,
    }))
    .digest('hex');
  return { ...model, hash };
}

function canonicalizeModelVersion(version?: string): string | undefined {
  if (!version) return undefined;
  const normalized = String(version).trim().toLowerCase();
  if (normalized === '1.0.0' || normalized === '1') return 'v1';
  return version;
}

function toCanonicalModel(model: RegisteredModel): RegisteredModel {
  return {
    ...model,
    modelId: canonicalizeModelId(model.modelId),
    version: canonicalizeModelVersion(model.version) || 'v1',
  };
}
