-- 079: DEFINITIVE Authority Register batch 3
-- Adds the next staged Authority Register expansion.
-- Focus: agreement architecture, THE LINE pass-through pricing boundary,
-- recovery datasets, digital-asset research anchors, regulated-industry overlays,
-- and real-estate pass-through standards.

INSERT INTO authority_register (
  authority_id, cite_tag, category, authority_type, jurisdiction, title, description,
  current_value, citation_text, source_name, source_url, publisher, effective_date,
  as_of_date, next_check_due, aliases, metadata
) VALUES
  ('AUTH.ABA.2023.PRIVATE_TARGET', '[ABA 2023 Private Target]', 'AgreementArchitecture', 'study', 'US', 'ABA Private Target Mergers and Acquisitions Deal Points Study 2023', 'Private-target deal-points study anchor for indemnity caps, baskets, materiality scrape, sandbagging, RWI, and survival-period mechanics.', '108 deals; 2022-Q1 2023; $30M-$750M', 'ABA Private Target Mergers and Acquisitions Deal Points Study 2023', 'American Bar Association', NULL, 'ABA Business Law Section', '2023-12-31', '2023-12-31', '2026-12-31', '["ABA Private Target", "indemnity cap", "materiality scrape"]'::jsonb, '{"source_family":"deal_terms","gates":["G8"],"model_slots":["M206","M207","M208","M209"]}'::jsonb),
  ('AUTH.SRS.2024.DEAL_TERMS', '[SRS 2024 Deal Terms]', 'AgreementArchitecture', 'study', 'US', 'SRS Acquiom 2024 M&A Deal Terms Study', 'Deal-terms study anchor for escrow, earnout, survival, RWI, and claims mechanics in private-target M&A.', '2100+ deals; $475B aggregate', 'SRS Acquiom 2024 M&A Deal Terms Study', 'SRS Acquiom', NULL, 'SRS Acquiom', '2024-12-31', '2024-12-31', '2026-12-31', '["SRS Deal Terms", "escrow", "earnout"]'::jsonb, '{"source_family":"deal_terms","gates":["G8","G9"],"model_slots":["M207","M208","M213"]}'::jsonb),
  ('AUTH.SRS.2025.WC_PPA', '[SRS 2025 WC PPA]', 'AgreementArchitecture', 'study', 'US', 'SRS Acquiom 2025 Working Capital Purchase Price Adjustment Study', 'Working-capital purchase-price-adjustment study anchor for closing-statement, PPA escrow, dispute, and true-up sequencing mechanics.', NULL, 'SRS Acquiom 2025 Working Capital Purchase Price Adjustment Study', 'SRS Acquiom', NULL, 'SRS Acquiom', '2025-12-31', '2025-12-31', '2026-12-31', '["working capital adjustment", "PPA escrow", "closing statement"]'::jsonb, '{"source_family":"deal_terms","gates":["G7","G8"],"model_slots":["M109","M208","M210"]}'::jsonb),
  ('AUTH.SRS.2024.CLAIMS_INSIGHTS', '[SRS 2024 Claims Insights]', 'AgreementArchitecture', 'study', 'US', 'SRS Acquiom 2024 Claims Insights Report', 'Claims-insights anchor for indemnity claims, escrow releases, survival periods, and dispute routing mechanics.', NULL, 'SRS Acquiom 2024 Claims Insights Report', 'SRS Acquiom', NULL, 'SRS Acquiom', '2024-12-31', '2024-12-31', '2026-12-31', '["claims insights", "escrow release", "indemnity claims"]'::jsonb, '{"source_family":"deal_terms","gates":["G8"],"model_slots":["M206","M207","M208"]}'::jsonb),
  ('AUTH.HOULIHAN.2023.TERMINATION_FEE', '[Houlihan 2023 TF]', 'AgreementArchitecture', 'study', 'US', 'Houlihan Lokey 2023 Transaction Termination Fee Study', 'Termination-fee and reverse-termination-fee market study anchor for break-fee economics.', '131 transactions', 'Houlihan Lokey 2023 Transaction Termination Fee Study', 'Houlihan Lokey', NULL, 'Houlihan Lokey', '2023-12-31', '2023-12-31', '2026-12-31', '["termination fee", "reverse termination fee"]'::jsonb, '{"source_family":"deal_terms","gates":["G7"],"model_slots":["M212"]}'::jsonb),
  ('AUTH.FENWICK.2023.ARBF', '[Fenwick 2023 ARBF]', 'AgreementArchitecture', 'study', 'US', 'Fenwick 2023 Antitrust Reverse Breakup Fee Analysis', 'Antitrust reverse-breakup-fee market analysis anchor for regulatory-failure fee economics.', NULL, 'Fenwick 2023 Antitrust Reverse Breakup Fee Analysis', 'Fenwick', NULL, 'Fenwick', '2023-12-31', '2023-12-31', '2026-12-31', '["antitrust reverse breakup fee", "ARBF"]'::jsonb, '{"source_family":"deal_terms","gates":["G7","G23"],"model_slots":["M212"]}'::jsonb),
  ('AUTH.CASE.BRAZEN_BELL_1997', '[Brazen v Bell Atlantic]', 'AgreementArchitecture', 'case_law', 'US-DE', 'Brazen v. Bell Atlantic Corp.', 'Delaware case-law anchor for liquidated-damages and termination-fee reasonableness scaffolding.', NULL, 'Brazen v. Bell Atlantic Corp.', 'Delaware Supreme Court', NULL, 'Delaware Courts', '1997-07-25', '1997-07-25', '2027-01-31', '["termination fee", "liquidated damages"]'::jsonb, '{"source_family":"delaware_case_law","gates":["G7"],"model_slots":["M212"]}'::jsonb),
  ('AUTH.CASE.TOPPS_2007', '[Topps, 2007]', 'AgreementArchitecture', 'case_law', 'US-DE', 'In re Topps Company Shareholders Litigation', 'Delaware deal-protection case-law anchor for go-shop, no-shop, and fiduciary-out mechanics.', NULL, 'In re Topps Company Shareholders Litigation', 'Delaware Court of Chancery', NULL, 'Delaware Courts', '2007-06-14', '2007-06-14', '2027-01-31', '["go-shop", "fiduciary out", "deal protection"]'::jsonb, '{"source_family":"delaware_case_law","gates":["G7"],"model_slots":["M211","M212"]}'::jsonb),
  ('AUTH.ABA.MODEL_SPA', '[ABA Model SPA]', 'AgreementArchitecture', 'model_form', 'US', 'ABA Model Stock Purchase Agreement', 'Model-form anchor for agreement-architecture term scaffolds and economic-term routing.', NULL, 'ABA Model Stock Purchase Agreement', 'American Bar Association', NULL, 'ABA Business Law Section', NULL, NULL, '2026-12-31', '["model SPA", "agreement terms"]'::jsonb, '{"source_family":"model_form","gates":["G1","G6","G7","G8","G9"],"model_slots":["M206","M207","M208","M210","M211","M212","M213","M217"]}'::jsonb),

  ('AUTH.EXCHANGE_ACT.15A', '[Exchange Act Section 15(a)]', 'PassThroughBoundary', 'statute', 'US', 'Exchange Act Section 15(a)', 'Broker registration authority used for THE LINE pass-through pricing and referral-fee boundary checks.', NULL, '15 U.S.C. Section 78o(a)', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/15/78o', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["broker registration", "transaction-based compensation"]'::jsonb, '{"source_family":"securities_law","gates":["G2","G30"],"model_slots":["M190","M195","M196","M205","M214","M215","M221"]}'::jsonb),
  ('AUTH.EXCHANGE_ACT.15B13', '[Exchange Act Section 15(b)(13)]', 'PassThroughBoundary', 'statute', 'US', 'Exchange Act Section 15(b)(13) M&A broker exemption', 'Federal M&A broker exemption authority used only to confirm that DEFINITIVE does not charge deal-tied human-service referral fees.', NULL, '15 U.S.C. Section 78o(b)(13)', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/15/78o', 'Legal Information Institute', '2023-03-29', '2023-03-29', '2027-01-31', '["M&A broker exemption", "state law not preempted"]'::jsonb, '{"source_family":"securities_law","gates":["G2"],"model_slots":["M205"]}'::jsonb),
  ('AUTH.EXCHANGE_ACT.29B', '[Exchange Act Section 29(b)]', 'PassThroughBoundary', 'statute', 'US', 'Exchange Act Section 29(b)', 'Void-contract authority used for high-severity THE LINE boundary checks.', NULL, '15 U.S.C. Section 78cc(b)', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/15/78cc', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["void contract", "securities law violation"]'::jsonb, '{"source_family":"securities_law","gates":["G2"],"model_slots":["M205"]}'::jsonb),
  ('AUTH.SEC.RANIERI_2013', '[SEC Ranieri 2013]', 'PassThroughBoundary', 'sec_order', 'US', 'In re Ranieri Partners LLC and Donald W. Phillips', 'SEC order anchor for transaction-based compensation and unregistered-broker risk in THE LINE boundary checks.', NULL, 'SEC Administrative Proceeding File No. 3-15234', 'U.S. Securities and Exchange Commission', 'https://www.sec.gov/litigation/admin/2013/34-69091.pdf', 'SEC', '2013-03-08', '2013-03-08', '2027-01-31', '["Ranieri", "unregistered broker", "transaction-based compensation"]'::jsonb, '{"source_family":"sec_order","gates":["G2"],"model_slots":["M205"]}'::jsonb),
  ('AUTH.SEC.PAUL_ANKA_NAL_1991', '[Paul Anka NAL]', 'PassThroughBoundary', 'no_action_letter', 'US', 'Paul Anka SEC no-action letter', 'SEC no-action letter anchor used as a narrow finder-fee historical reference; not a basis for DEFINITIVE to accept human-service referral compensation.', NULL, 'Paul Anka SEC No-Action Letter (1991)', 'U.S. Securities and Exchange Commission', NULL, 'SEC', '1991-07-24', '1991-07-24', '2027-01-31', '["Paul Anka", "finder", "no-action letter"]'::jsonb, '{"source_family":"sec_no_action","gates":["G2"],"model_slots":["M205"]}'::jsonb),
  ('AUTH.ABA.MODEL_RULE_7_2B', '[ABA Model Rule 7.2(b)]', 'PassThroughBoundary', 'model_rule', 'US', 'ABA Model Rule 7.2(b)', 'Professional-conduct model-rule anchor for legal-service referral-fee boundary checks.', NULL, 'ABA Model Rule of Professional Conduct 7.2(b)', 'American Bar Association', 'https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/rule_7_2_communications_concerning_a_lawyers_services/', 'American Bar Association', NULL, NULL, '2027-01-31', '["legal referral fee", "lawyer advertising"]'::jsonb, '{"source_family":"professional_responsibility","gates":["G10","G30"],"model_slots":["M214","M215","M221"]}'::jsonb),
  ('AUTH.NASAA.MA_BROKER_MODEL_RULE', '[NASAA M&A Broker Model Rule]', 'PassThroughBoundary', 'model_rule', 'US', 'NASAA M&A broker model exemption rule', 'State-law exemption map anchor for THE LINE boundary checks around M&A broker and finder activity.', NULL, 'NASAA M&A Broker Model Rule', 'North American Securities Administrators Association', NULL, 'NASAA', NULL, NULL, '2027-01-31', '["NASAA", "state M&A broker exemption"]'::jsonb, '{"source_family":"state_exemption_map","gates":["G2"],"model_slots":["M205"]}'::jsonb),

  ('AUTH.MOODYS.URD_2006', '[Moodys URD 2006]', 'RecoveryData', 'subscription_dataset', 'US', 'Moodys Ultimate Recovery Database Special Comment 2006', 'Recovery dataset anchor for claims-trading, recovery regression, and distressed-waterfall scaffolds.', 'Subscription/source validation required before production reliance', 'Moodys Ultimate Recovery Database Special Comment 2006', 'Moodys', NULL, 'Moodys', '2006-12-31', '2006-12-31', '2026-12-31', '["ultimate recovery database", "URD"]'::jsonb, '{"source_family":"recovery_data","gates":["G28"],"model_slots":["M153","M157","M166"]}'::jsonb),
  ('AUTH.SP.LOSSSTATS', '[S&P LossStats]', 'RecoveryData', 'subscription_dataset', 'US', 'S&P Global LossStats', 'Recovery and default dataset anchor for restructuring, claims, and waterfall benchmarking.', 'Subscription/source validation required before production reliance', 'S&P Global LossStats', 'S&P Global / Morningstar PitchBook LCD', NULL, 'S&P Global', NULL, NULL, '2026-12-31', '["LossStats", "default recovery"]'::jsonb, '{"source_family":"recovery_data","gates":["G28"],"model_slots":["M153","M157","M166","M168"]}'::jsonb),
  ('AUTH.MORNINGSTAR.LSTA_US_LLI', '[Morningstar LSTA LLI]', 'RecoveryData', 'index', 'US', 'Morningstar LSTA US Leveraged Loan Index', 'Leveraged-loan index anchor for credit-market, default-rate, and recovery-context scaffolds.', NULL, 'Morningstar LSTA US Leveraged Loan Index', 'Morningstar PitchBook LCD', NULL, 'Morningstar', NULL, NULL, '2026-12-31', '["leveraged loan index", "LSTA"]'::jsonb, '{"source_family":"credit_index","gates":["G28","G29"],"model_slots":["M166","M168","M179"]}'::jsonb),
  ('AUTH.LOPUCKI.BRD', '[LoPucki BRD]', 'RecoveryData', 'dataset', 'US', 'LoPucki Bankruptcy Research Database', 'Bankruptcy research dataset anchor for Chapter 22 recidivism and post-emergence history scaffolds.', NULL, 'LoPucki Bankruptcy Research Database', 'UCLA School of Law', 'https://lopucki.law.ufl.edu/', 'UCLA / University of Florida', NULL, NULL, '2026-12-31', '["bankruptcy research database", "Chapter 22"]'::jsonb, '{"source_family":"bankruptcy_dataset","gates":["G28"],"model_slots":["M168"]}'::jsonb),
  ('AUTH.FRBP.3001', '[FRBP 3001]', 'BankruptcyCode', 'federal_rule', 'US', 'Federal Rule of Bankruptcy Procedure 3001', 'Claims filing and transfer rule anchor for claims-trading and transfer mechanics.', NULL, 'Federal Rule of Bankruptcy Procedure 3001', 'Legal Information Institute', 'https://www.law.cornell.edu/rules/frbp/rule_3001', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["proof of claim", "claims transfer"]'::jsonb, '{"source_family":"bankruptcy_rule","gates":["G28"],"model_slots":["M166"]}'::jsonb),

  ('AUTH.GENIUS.ACT_2025', '[GENIUS Act 2025]', 'DigitalAssets', 'statute', 'US', 'GENIUS Act stablecoin framework', 'Stablecoin statutory framework anchor for research-only payment-stablecoin issuer scaffolds.', 'Research-only until implementation and rulemaking stabilize', 'GENIUS Act 2025', 'Congress.gov', 'https://www.congress.gov/', 'U.S. Congress', '2025-07-18', '2025-07-18', '2026-08-31', '["GENIUS Act", "payment stablecoin"]'::jsonb, '{"source_family":"digital_asset_statute","gates":["G30"],"model_slots":["M175"]}'::jsonb),
  ('AUTH.CLARITY.HR3633_2025', '[CLARITY Act H.R. 3633]', 'DigitalAssets', 'bill', 'US', 'CLARITY Act H.R. 3633', 'Digital-asset market-structure bill anchor for research-only token-taxonomy scaffolds.', 'Research-only; enactment status must be revalidated before reliance', 'H.R. 3633 CLARITY Act', 'Congress.gov', 'https://www.congress.gov/bill/119th-congress/house-bill/3633', 'U.S. Congress', '2025-07-17', '2025-07-17', '2026-08-31', '["CLARITY Act", "digital asset market structure"]'::jsonb, '{"source_family":"digital_asset_statute","gates":["G30"],"model_slots":["M174"]}'::jsonb),
  ('AUTH.SEC.PROJECT_CRYPTO_2025', '[SEC Project Crypto]', 'DigitalAssets', 'agency_statement', 'US', 'SEC Project Crypto', 'SEC project and speech anchor for research-only token-taxonomy and tokenization scaffolds.', 'Research-only', 'SEC Project Crypto public statements', 'U.S. Securities and Exchange Commission', 'https://www.sec.gov/', 'SEC', '2025-11-12', '2025-11-12', '2026-08-31', '["Project Crypto", "token taxonomy"]'::jsonb, '{"source_family":"digital_asset_agency_statement","gates":["G30"],"model_slots":["M174"]}'::jsonb),
  ('AUTH.SEC.TOKENIZATION_STATEMENT_2026', '[SEC Tokenization Statement]', 'DigitalAssets', 'agency_statement', 'US', 'SEC Staff Tokenization Statement', 'SEC staff statement anchor for research-only tokenization scaffolds.', 'Research-only', 'SEC Staff Tokenization Statement', 'U.S. Securities and Exchange Commission', 'https://www.sec.gov/', 'SEC', '2026-01-28', '2026-01-28', '2026-08-31', '["tokenization", "digital assets"]'::jsonb, '{"source_family":"digital_asset_agency_statement","gates":["G30"],"model_slots":["M174"]}'::jsonb),
  ('AUTH.IRS.REVPROC_2025_31', '[Rev. Proc. 2025-31]', 'DigitalAssets', 'irs_guidance', 'US', 'IRS Revenue Procedure 2025-31', 'IRS digital-asset staking trust safe-harbor guidance anchor for research-only tax and reporting scaffolds.', 'Research-only', 'IRS Revenue Procedure 2025-31', 'Internal Revenue Service', 'https://www.irs.gov/', 'IRS', '2025-07-14', '2025-07-14', '2026-08-31', '["digital asset staking", "safe harbor"]'::jsonb, '{"source_family":"digital_asset_tax_guidance","gates":["G30"],"model_slots":["M174","M176"]}'::jsonb),
  ('AUTH.TD_10000.DIGITAL_ASSET_REPORTING', '[T.D. 10000]', 'DigitalAssets', 'treasury_regulation', 'US', 'T.D. 10000 digital-asset broker reporting regulations', 'Treasury final-regulation anchor for research-only Form 1099-DA and broker-reporting scaffolds.', 'Research-only', 'T.D. 10000 / IRC Section 6045 digital-asset broker reporting', 'Internal Revenue Service / Treasury', 'https://www.irs.gov/', 'Treasury / IRS', '2024-07-09', '2024-07-09', '2026-08-31', '["1099-DA", "digital asset broker reporting"]'::jsonb, '{"source_family":"digital_asset_tax_guidance","gates":["G30"],"model_slots":["M176"]}'::jsonb),

  ('AUTH.HIPAA.45_CFR_160_164', '[HIPAA Privacy/Security]', 'RegulatedIndustries', 'regulation', 'US', 'HIPAA Administrative Simplification regulations', 'Healthcare privacy and security regulatory anchor for regulated-industry overlay screening.', NULL, '45 CFR Parts 160 and 164', 'eCFR', 'https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C', 'eCFR', NULL, NULL, '2027-01-31', '["HIPAA", "privacy", "security"]'::jsonb, '{"source_family":"regulated_industry_healthcare","gates":["G24"],"model_slots":["M130","M131"]}'::jsonb),
  ('AUTH.STARK.42_USC_1395NN', '[Stark Law]', 'RegulatedIndustries', 'statute', 'US', 'Physician self-referral law', 'Healthcare Stark Law anchor for regulated-industry overlay issue spotting.', NULL, '42 U.S.C. Section 1395nn', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/42/1395nn', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["Stark", "self referral"]'::jsonb, '{"source_family":"regulated_industry_healthcare","gates":["G24"],"model_slots":["M130"]}'::jsonb),
  ('AUTH.AKS.42_USC_1320A_7B', '[Anti-Kickback Statute]', 'RegulatedIndustries', 'statute', 'US', 'Federal Anti-Kickback Statute', 'Healthcare anti-kickback statutory anchor for regulated-industry overlay issue spotting.', NULL, '42 U.S.C. Section 1320a-7b', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/42/1320a-7b', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["AKS", "anti-kickback"]'::jsonb, '{"source_family":"regulated_industry_healthcare","gates":["G24"],"model_slots":["M130"]}'::jsonb),
  ('AUTH.ITAR.22_CFR_120', '[ITAR 22 CFR Part 120]', 'RegulatedIndustries', 'regulation', 'US', 'International Traffic in Arms Regulations definitions', 'Defense and export-control regulatory anchor for regulated-industry overlay screening.', NULL, '22 CFR Part 120', 'eCFR', 'https://www.ecfr.gov/current/title-22/chapter-I/subchapter-M/part-120', 'eCFR', NULL, NULL, '2027-01-31', '["ITAR", "defense articles"]'::jsonb, '{"source_family":"regulated_industry_defense","gates":["G24"],"model_slots":["M132"]}'::jsonb),
  ('AUTH.EAR.15_CFR_730', '[EAR 15 CFR Part 730]', 'RegulatedIndustries', 'regulation', 'US', 'Export Administration Regulations general information', 'Export-control regulatory anchor for regulated-industry overlay screening.', NULL, '15 CFR Part 730', 'eCFR', 'https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-730', 'eCFR', NULL, NULL, '2027-01-31', '["EAR", "export controls"]'::jsonb, '{"source_family":"regulated_industry_defense","gates":["G24"],"model_slots":["M132"]}'::jsonb),
  ('AUTH.FERC.203', '[FPA Section 203]', 'RegulatedIndustries', 'statute', 'US', 'Federal Power Act Section 203', 'Energy transaction approval authority for regulated-industry and project-finance overlay screening.', NULL, '16 U.S.C. Section 824b', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/16/824b', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["FERC 203", "energy merger approval"]'::jsonb, '{"source_family":"regulated_industry_energy","gates":["G24","G30"],"model_slots":["M107","M173"]}'::jsonb),
  ('AUTH.FCC.214', '[Communications Act Section 214]', 'RegulatedIndustries', 'statute', 'US', 'Communications Act Section 214', 'Telecommunications transfer and authorization anchor for regulated-industry overlay screening.', NULL, '47 U.S.C. Section 214', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/47/214', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["FCC 214", "telecom authorization"]'::jsonb, '{"source_family":"regulated_industry_telecom","gates":["G24"],"model_slots":["M107"]}'::jsonb),
  ('AUTH.FCC.310', '[Communications Act Section 310]', 'RegulatedIndustries', 'statute', 'US', 'Communications Act Section 310', 'Broadcast and wireless license transfer/foreign-ownership anchor for regulated-industry overlay screening.', NULL, '47 U.S.C. Section 310', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/47/310', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["FCC 310", "license transfer", "foreign ownership"]'::jsonb, '{"source_family":"regulated_industry_telecom","gates":["G24"],"model_slots":["M107"]}'::jsonb),
  ('AUTH.BHCA.12_USC_1842', '[BHCA Section 3]', 'RegulatedIndustries', 'statute', 'US', 'Bank Holding Company Act Section 3', 'Bank-control transaction statutory anchor for financial-services regulated-industry overlay screening.', NULL, '12 U.S.C. Section 1842', 'U.S. Code', 'https://www.law.cornell.edu/uscode/text/12/1842', 'Legal Information Institute', NULL, NULL, '2027-01-31', '["BHCA", "bank holding company"]'::jsonb, '{"source_family":"regulated_industry_financial_services","gates":["G24"],"model_slots":["M107"]}'::jsonb),
  ('AUTH.REG_Y.12_CFR_225', '[Regulation Y]', 'RegulatedIndustries', 'regulation', 'US', 'Federal Reserve Regulation Y', 'Bank holding company regulatory anchor for financial-services regulated-industry overlay screening.', NULL, '12 CFR Part 225', 'eCFR', 'https://www.ecfr.gov/current/title-12/chapter-II/subchapter-A/part-225', 'eCFR', NULL, NULL, '2027-01-31', '["Regulation Y", "bank holding company"]'::jsonb, '{"source_family":"regulated_industry_financial_services","gates":["G24"],"model_slots":["M107"]}'::jsonb),

  ('AUTH.ASC.842', '[ASC 842]', 'RealEstate', 'accounting_standard', 'US', 'ASC 842 leases', 'Lease-accounting standard anchor for sale-leaseback and OpCo/PropCo mechanics.', NULL, 'ASC 842 Leases', 'Financial Accounting Standards Board', NULL, 'FASB', NULL, NULL, '2027-01-31', '["ASC 842", "sale leaseback"]'::jsonb, '{"source_family":"accounting_standard","gates":["G30"],"model_slots":["M171","M194"]}'::jsonb),
  ('AUTH.ASTM.E1527', '[ASTM E1527]', 'RealEstate', 'industry_standard', 'US', 'ASTM E1527 Phase I Environmental Site Assessment standard', 'Environmental site assessment standard anchor for pass-through environmental diligence inputs.', NULL, 'ASTM E1527', 'ASTM International', NULL, 'ASTM International', NULL, NULL, '2027-01-31', '["Phase I ESA", "environmental assessment"]'::jsonb, '{"source_family":"real_estate_standard","gates":["G30"],"model_slots":["M195"]}'::jsonb),
  ('AUTH.ASTM.E2018', '[ASTM E2018]', 'RealEstate', 'industry_standard', 'US', 'ASTM E2018 Property Condition Assessment standard', 'Property condition assessment standard anchor for pass-through PCA reserve modeling.', NULL, 'ASTM E2018', 'ASTM International', NULL, 'ASTM International', NULL, NULL, '2027-01-31', '["PCA", "property condition assessment"]'::jsonb, '{"source_family":"real_estate_standard","gates":["G30"],"model_slots":["M198"]}'::jsonb)
ON CONFLICT (authority_id) DO UPDATE
  SET cite_tag = EXCLUDED.cite_tag,
      category = EXCLUDED.category,
      authority_type = EXCLUDED.authority_type,
      jurisdiction = EXCLUDED.jurisdiction,
      title = EXCLUDED.title,
      description = EXCLUDED.description,
      current_value = EXCLUDED.current_value,
      citation_text = EXCLUDED.citation_text,
      source_name = EXCLUDED.source_name,
      source_url = EXCLUDED.source_url,
      publisher = EXCLUDED.publisher,
      effective_date = EXCLUDED.effective_date,
      as_of_date = EXCLUDED.as_of_date,
      next_check_due = EXCLUDED.next_check_due,
      aliases = EXCLUDED.aliases,
      metadata = EXCLUDED.metadata,
      updated_at = NOW(),
      status = 'active',
      validation_status = 'founder_reviewed';
