import PublicLayout from '../../components/public/PublicLayout';

export default function Terms() {
  return (
    <PublicLayout>
      <section className="max-w-[800px] mx-auto px-10 pt-20 pb-20 max-md:px-5 max-md:pt-12 max-md:pb-12">
        <h1 className="font-serif text-[clamp(32px,3.5vw,48px)] font-black tracking-[-0.03em] mb-10 m-0">
          Terms of Service
        </h1>
        <div className="space-y-8 text-[15px] text-[#4A4843] leading-[1.7]">
          <p className="m-0">
            <strong className="text-[#1A1A18]">Last updated:</strong> February 2026
          </p>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">The service</h2>
            <p className="m-0">
              smbx.ai provides AI-powered deal advisory tools including business valuations,
              financial analysis, document generation, and deal management. By using the service,
              you agree to these terms.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Not financial advice</h2>
            <p className="m-0">
              smbx.ai provides analytical tools and information to support your decision-making.
              Our work product is not a substitute for professional legal, financial, or tax advice.
              We recommend consulting qualified professionals before making significant business
              or financial decisions.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Your account</h2>
            <p className="m-0">
              You are responsible for maintaining the security of your account credentials.
              You agree to provide accurate information and to keep your account information
              up to date. You may not share your account with others or use another person&apos;s
              account without permission.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Payments</h2>
            <p className="m-0">
              smbx.ai uses a pay-as-you-go wallet model. Credits are purchased in advance and
              consumed as you use paid features. Credits do not expire. Refunds are available
              if our work product does not meet professional standards.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Your content</h2>
            <p className="m-0">
              You retain ownership of all business information, documents, and data you provide
              to the service. You grant smbx.ai a limited license to process this information
              solely for the purpose of providing the service to you.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Work product</h2>
            <p className="m-0">
              Valuations, CIMs, financial analyses, and other documents generated by the service
              are yours to use, distribute, and modify as you see fit. You are responsible for
              verifying the accuracy of any work product before relying on it.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Service providers</h2>
            <p className="m-0">
              Attorneys, CPAs, and other service providers invited to a deal room by a paying
              client receive access at no cost. Service provider access is limited to the
              specific deals they are invited to participate in.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Limitation of liability</h2>
            <p className="m-0">
              smbx.ai is provided &ldquo;as is.&rdquo; We do not guarantee specific outcomes
              from using the service. Our total liability is limited to the amount you have
              paid for the service in the preceding 12 months.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Changes</h2>
            <p className="m-0">
              We may update these terms from time to time. Continued use of the service after
              changes constitutes acceptance. Material changes will be communicated via email.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-xl font-bold text-[#1A1A18] mb-3 m-0">Contact</h2>
            <p className="m-0">
              Questions about these terms? Email us at{' '}
              <a href="mailto:hello@smbx.ai" className="text-[#DA7756] underline">hello@smbx.ai</a>.
            </p>
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
